Checkstyle
DenisVerkhoturov/metamer pull request #11
Opened 2019-04-05 14:38 UTC by AnBrusn

2019-04-05 21:46 UTC, DenisVerkhoturov requested changes
Огонь! :+1: 
Спасибо, с самим конфигом полностью согласен, а с подключением попрошу внести пару изменений=)

Так же, пожалуйста, подтяни `master` и сосквош в один коммит, не забудь переименовать итоговый коммит.

2019-04-05 21:46 UTC, DenisVerkhoturov commented on build.gradle
> +apply plugin: 'checkstyle'
Предлагаю придерживаться одного стиля, если мы уже начали подключать `gradle`-плагины используя синтаксис замыкания, то давайте и дальше ему следовать. Перемести, пожалуйста, `checkstyle` в блок `plugins`  выше:
```groovy
plugins {
    id 'java'
    id 'checkstyle'
}
```

2019-04-05 21:46 UTC, DenisVerkhoturov commented on build.gradle
> +    source ='src/test/java'
Так как сорцы у нас располагаются по стандартным путям, мы можем не указывать это явно. Поэтому мы можем удалить пункты `checkstyleMain` и `checkstyleTest`, нас удовлетворяют значения по умолчанию.

2019-04-05 21:46 UTC, DenisVerkhoturov commented on build.gradle
> +    configFile file("config/checkstyle/checkstyle.xml")
Путь `config/checkstyle/checkstyle.xml` - это путь конфигурационного файла по умолчанию, поэтому явное его указание мы тоже можем опустиь.

2019-04-07 10:36 UTC, alex-klimina submitted a review, later dismissed

2019-04-07 19:10 UTC, DenisVerkhoturov approved these changes

2019-04-07 19:11 UTC, DenisVerkhoturov approved these changes

2019-04-07 19:13 UTC, merged

2019-04-12 12:30 UTC, DenisVerkhoturov commented
![](https://github.trello.services/images/mini-trello-icon.png) [Подключить checkstyle](https://trello.com/c/GUIBelvy/20-%D0%BF%D0%BE%D0%B4%D0%BA%D0%BB%D1%8E%D1%87%D0%B8%D1%82%D1%8C-checkstyle)