PITest
DenisVerkhoturov/metamer pull request #16
Opened 2019-04-12 18:05 UTC by ShapovalovaIrina

2019-04-12 20:58 UTC, DenisVerkhoturov requested changes
Спасибо за пулл-реквест, отлично! :+1:

Ниже ты можешь найти пару комментариев. Кроме того, моя вина, я не достаточно проинвестигировал тему с отправкой `coverage` репортов в формате, который выдает `pitest`. Поэтому пока мы отказываемся от шага с репортингом, оставляем только само подключение `pitest`, будем пока руками в него тыкаться и проверять, что там и как у нас с покрытием в приложении. Однако, позже мы, вероятно, вернемся к задаче репортинга.

2019-04-12 20:58 UTC, DenisVerkhoturov commented on build.gradle
> +        classpath 'info.solidsoft.gradle.pitest:gradle-pitest-plugin:1.4.0'
На самом деле, нам не нужно явно указывать зависимость от этого плагина в разделе `buildscript`, если мы просто явно укажем версию в секции `plugins`, а здесь оставь, пожалуйста, только:
```gradle
buildscript {
    configurations.maybeCreate('pitest')
    dependencies {
        pitest 'org.pitest:pitest-junit5-plugin:0.8'
    }
}
```

2019-04-12 20:58 UTC, DenisVerkhoturov commented on build.gradle
> +    id 'jacoco'
Идея подключения `pitest` заключалась в том, что бы заменить им менее репрезентативные `coverage` репорты от `jacoco`.

Если ты помнишь, в понедельник я как раз объяснял, что `jacoco` считает `coverage` на основе того, сколько раз в результате выполнения тестов вызвалась каждая конкретная строчка кода. Что не очень то показательно, ведь можно написать всего один тест, который по факту затронет практически всю логику приложения, чем очень даже обеспечит высокий `coverage` по версии `jacoco`, однако при этом он вполне может даже ничего путем и не проверять.

В отличае от `jacoco`, `pitest` порождает поколения "мутантов", изменяя определенным образом исходники, а затем запускает против них тесты, и проверяет, упал ли хотя бы какой-то из тестов. Если какой-то из них упал, "мутант" считается убитым, если все тесты прошли - "выжившим". Соответственно, `coverage` он считает исходя из отношения "убитых мутантов" ко всем "мутантам". В результате получается картина, когда мы точно знаем, какие потенциальные баги могут пропустить наши тесты.

Удали, пожалуйста, логику подключения `jacoco`. На данный момент, к сожалению, я не нашел способ использовать `piptest` формат для репортинга на `codacy`. Но я открыл `issue`, посмотрим, что нам ответят. Я буду следить за этим моментом. Возможно, позже мы вернемся к вопросу репортинга `coverage` на `codacy`, либо в формате `jacoco`, либо придумаем что-нибудь с `pitest`. Май бэд, можно было предположить, что такая проблема возникнет.

2019-04-12 20:58 UTC, DenisVerkhoturov commented on build.gradle
> +apply plugin: 'info.solidsoft.pitest'
Перенеси, пожалуйста, подключение плагина `pitest` в секцию `plugins`, где у нас подключаются остальные плагины. И добавь, пожалуйста, к нему версию, как я писал выше:
```gradle
plugins {
    /* other plugins */
    id 'info.solidsoft.pitest' version '1.4.0'
}
```

2019-04-12 20:58 UTC, DenisVerkhoturov commented on build.gradle
> +    }
Честно говоря, не знаю, для чего ты подключаешь альтернативные репозитории. На данный момент они определенно нам не нужны, удали, пожалуйста. То есть действительн онужен нам только `mavenCentral`.

2019-04-12 20:58 UTC, DenisVerkhoturov commented on build.gradle
> +    threads = 4
Включи еще, пожалуйста, все мутаторы, чтобы повысить агрессивность тестов. Там, в том числе, будут включены и эксперементальные фичи, что возможно даст ложные срабатывания, но мы можем себе это позволить=)

```gradle
pitest {
    mutators = ['ALL']
    /* other properties */
}
```

2019-04-12 20:58 UTC, DenisVerkhoturov commented on build.gradle
> +            "${buildDir}/reports/jacoco/test/jacocoTestReport.xml"
Ну и соответственно, раз у нас накрылась отправка `coverage` репортов, эта таска нам тоже пока не нужна. Вернемся к ней позже, когда решим вопрос с репортингом. На данном этапе обойдемся локальным `test-coverage`-ом.

2019-04-12 20:58 UTC, DenisVerkhoturov commented on .travis.yml
> +  - java -jar ~/codacy-coverage-reporter-assembly.jar report -l Java -r build/reports/jacoco/test/jacocoTestReport.xml
По той же причине, что ты не делаем сейчас репортинг на `codacy`, часть конфигурации `after_success`, тоже, пожалуйста, удали.

**NB**: Для истории. Предполагалось, что таску в `build.gradle` мы делаем как раз для того, чтобы в `after_success` просто вызывать ее, и тем самым избежать хардкода. То есть, когда мы вернемся к задаче репортинга на `codacy` мы будем выполнять здесь `bash gradlew sendCoverageToCodacy`.

2019-04-13 08:28 UTC, DenisVerkhoturov approved these changes

2019-04-13 08:37 UTC, alex-klimina approved these changes

2019-04-13 08:46 UTC, merged

2019-04-13 08:48 UTC, DenisVerkhoturov commented
![](https://github.trello.services/images/mini-trello-icon.png) [Подключить test coverage](https://trello.com/c/7fH464fb/29-%D0%BF%D0%BE%D0%B4%D0%BA%D0%BB%D1%8E%D1%87%D0%B8%D1%82%D1%8C-test-coverage)