Interfaces
DenisVerkhoturov/metamer pull request #23
Opened 2019-04-19 13:23 UTC by Sonik-zirael

Задание ещё не выполнено до конца, но просили открыть pull-request ещё на стадии работы
К тому же вдруг я немного неправильно поняла структуру диаграммы 🤔 
Да и по работе с дженериками есть вопросы...

2019-04-19 13:31 UTC, Sonik-zirael commented on src/main/java/metamer/io/FileWriter.java
> +            f.show((Record)lines);
Вот в этой строке не работает приведение типов, а если не указывать его явно, то ошибка инстанцирования

2019-04-19 14:14 UTC, Sonik-zirael commented on src/main/java/metamer/io/FileReader.java
> +        return Stream.of();
А вот тут проблема с возвращением прочитанного, так как оказывается нельзя сделать `return f.read(Files.lines(path))`

2019-04-19 19:08 UTC, DenisVerkhoturov commented on src/main/java/metamer/io/FileWriter.java
> +            f.show((Record)lines);
Основаная ошибка здесь в том, что ты создаешь объект типа `Fasta` и используешь его для записи. И в этом месте у нас расхождение контрактов - `Fasta#show` хочет `Record`, а у мы пытаемся какой-то неизвестный `T` в него передать. Соответсвенно сисета типов сразу говорит, что мы делаем что-то не то.

В этом контексте, нам уже не интересны никакие `Fasta` и `FastQ`, мы знать о них не хотим. В этом месте мы готовы работать с парсером любого типа `T`. И у нас в объекте уже есть такой - `this.parser`. Соответственно его мы используем для преобразования `T` к `String`.

Так же я все же настаиваю на том, что нам не нужно проверять, что нам дали файл с правильным расширением файла. Очень часто файлы вообще без расширения или с некорректным расширением, нас это должно мало интересовать, ведь если я переименую файл `my_awesome_genome.fasta` в `my_awesome_genome`, контент внутри все еще будет в формате `fasta`. И наоборот, если я переименую `definitely_not_a_virus.exe` в `definitely_not_a_virus.fasta`, контент в нем не станет внезапно в формате `fasta`. Поэтому расширение файла - это информация для пользователя, мы недолжны завязывать на это логику валидации. Нужно будет донести эту мысль так же @AnBrusn и @ShapovalovaIrina. Причем это справедливо и при чтении и при письме.

В конечном итоге, на самом деле, у нас будет простая реализация:
```java
package metamer.io;

import java.nio.file.Path;
import java.util.stream.Stream;

public class FileWriter<T> implements Writer<T> {
    private final Path path;
    private final Parser<T> parser;

    public Parser<T> parser() {
        return this.parser;
    }

    public Path path() {
        return this.path;
    }

    public FileWriter(final Path path, final Parser<T> parser) {
        this.path = path;
        this.parser = parser;
    }

    public void write(Stream<T> records) {
        final Stream<String> lines = this.parser().show(records);
        /* Remember to write those lines to the file under this.path() */
    }
}
```

2019-04-19 19:18 UTC, DenisVerkhoturov commented on src/main/java/metamer/io/FileReader.java
> +        return Stream.of();
Тут тоже такой момент, мы выносим `Parser` как контракт как раз чтобы предоставить полиморфный способ работы с любым фомрматом. Не только `Fasta` и `FastQ`, но и любые возможные форматы, которые могут появиться позже. Для того, чтобы наши ридеры/врайтеры стали поддерживать и их, нужно просто описать реализацию парсинга - ничего больше. Мы просто описываем новй формат и уже можем писать и читать его. 

На самом деле все очень просто:
```java
package metamer.io;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.stream.Stream;

public class FileReader<T> implements Reader {
    private final Path path;
    private final Parser<T> parser;

    public FileReader(final Path path, final Parser<T> parser) {
        this.path = path;
        this.parser = parser;
    }

    public Path path() {
        return this.path;
    }

    public Parser<T> parser() {
        return this.parser;
    }

    public Stream<T> read() {
        try (final Stream<String> lines = Files.lines(path)) {
            return this.parser().read(lines);
        } catch (IOException e) {
            throw new RuntimeException("Something shitty has just happened...");
        }
    }
}
```

#### NB
Полиморфизм - **бро**, ветвление - **не бро**!=)

2019-04-21 10:52 UTC, DenisVerkhoturov requested changes
Спасибо, у нас наконец появляется `IO` здорового человека! :+1:

Ниже ты можешь найти некоторые рекоммендации по улучшению, а так же я попрошу тебя, пройтись по файлам и удалить весь код, который стал неиспользуемым, например, много импортов теперь объявленны просто, но не используются.

2019-04-21 10:52 UTC, DenisVerkhoturov commented on src/main/java/metamer/io/FileWriter.java
> +        File file = new File(path.toString());
Есть более последовательный способ получить `File` из `Path`:
```java
final Path path = Paths.get("my/awesome/path");
final File file = path.toFile();
```

2019-04-21 10:52 UTC, DenisVerkhoturov commented on src/main/java/metamer/fasta/Fasta.java
> +        return Stream.of(record.toString());
Метод `Record#toString` все же должен работать несколько иначе. Этот метод исключительно одну цель выполняет и это - `debug`, поэтому важно, чтобы он сохранял информацию о типе, чаще всего его реализуют так, чтобы он показывал что-то такое:
`Book(title = "Structure andInterpretationof Computer Programs", authors = [Author(name = "Harold", middlename = "", surname = "Abelson"), Author(name = "Gerald", middlename = "Jay", surname =  "Sussman")])"`

А вот приведение к строке в терминах какого-то конкретного формата - это уже другая логика. Поэтому, реализуй, пожалуйста, логику построения строки в парсере так, чтобы она подходила под формат, а в самом рекорде - так, чтобы она подходила под принятый способ реализации.

2019-04-21 10:52 UTC, DenisVerkhoturov commented on src/main/java/metamer/fasta/Fasta.java
>      private final String SP = System.getProperty("line.separator");
Эта строчка была тут до тебя, но раз я разглядел ее только сейчас, "отдуваться" тебе=) это лучше заменить на вызов соответствующего метода:
```java
System.lineSeparator()
```

Но вообще говоря, `SP` вроде сейчас не используется в рамках этого класса, поэтому его, конечно, лучше выпилить.

2019-04-21 10:52 UTC, DenisVerkhoturov commented on src/main/java/metamer/fasta/Fasta.java
> +//import java.io.BufferedWriter;
Держать в репозитории закомментированный код - это не законно!>_<

Не волнуйся, `git` все помнит, если ты опасаешься, что что-то забудешь и поэтому  "пусть пока просто закомментированным побудет", то нет=) Всегда можно будет посмотреть версию файла до твоих изменений и вообще в любой момент истории репозитория. Поэтому, давайте договоримся, @Sonik-zirael, @AnBrusn, @ShapovalovaIrina, в репозитории неиспользуемый код не храним, если что-то больше не нужно, сразу удаляем, хорошо?=)

2019-04-21 10:52 UTC, DenisVerkhoturov commented on src/main/java/metamer/fasta/Fasta.java
> +    public Fasta parse() {
Я так понимаю, что по `UML` это метод `Fasta#parser()`. Исправь, пожалуйста, название и второй момент - предполагалось, что этот метод выполняет роль `getInstance` паттерна `Singleton`. То есть, в чем логика? Парсеры у нас не имеют изменяемого внутреннего состояния, поэтому создавать несколько их инстансев не имеет смысла - со всем может справиться и один инстанс. Можно было в таком случае и вовсе сделать все его методы статическими? Вот только, нельзя статические методы описать контрактом, в этом `java` тоже дает слабину. То есть в ней синтаксиса объявления единственого экземпляра и нет возможности объявиьт контракт на статические методы. Поэтому остается вариант с самостоятельной реализацией паттерна `Singleton` (подойдет даже наивная реализация), или создавать инстанс каждый раз новый (тут момент в том, что как таковой инстанс нам не нужен для всей логики парсинга, так как у него нет изменяемого состояния).
```java
public class Fasta implements Parser<Record> {
    private static final Fasta instance = new Fasta();
    
    private Fasta() {}
    
    public static Fasta parser() {
        return instance;
    }
}
```
И затем соответственно мы получаем всегда один и тот же инстанс и не делаем работу по инициализации:
```java
final Fasta parser_1 = Fasta.parser();
final Fasta parser_2 = Fasta.parser();
assert parser_1 == parser_2;
```

2019-04-21 10:52 UTC, DenisVerkhoturov commented on src/main/java/metamer/fasta/Fasta.java
> +            try {
Этот `try` несет какую-то осмысленную логику сейчас - это правда, но вот внешний `try`, больше не имеет смысла в этом контексте, так как там была какая-то работа с файловой сиситемой. Сейчас же в контексте парсера, мы понятия не имеем ни о каких файлах. Соответственно, поля связанные с этой логикой тоже необходимо удалить.

В контексте этой логики, мы решаем одну маленькую задачу - превратить строки в рекорды.

2019-04-21 10:52 UTC, DenisVerkhoturov commented on src/main/java/metamer/fasta/Fasta.java
> +                            tmpInformation = str.substring(str.indexOf(" ", 0) + 1);
Тут нам нужно решить только часть задачи на самом деле - разбить строки на группы списков строк, так чтобы в каждом списке оказались все строки нужные для формирования записи, а затем, для непосредственного формирования записи мы вызываем метод `Fasta#read(List<String>)`, который уже заменяет нам группы строк относящихся к конкретной записи на объекты класса `fasta.Record`.

2019-04-21 10:52 UTC, DenisVerkhoturov commented on src/main/java/metamer/fasta/Fasta.java
> +            }
Собственно, логика приведения к строке, как и логика приведения к объекту должна быть реализована одинаковым образом - разбиваем работу на составляющие, а для составляющих вызываем простой метод, который работает с составляющей.

В общем тут мы должны вызывать метод `Fasta#show(Record)` для каждого рекорда и собирать получившиеся строки в одну строку=)
По сути реализация этого метода выглядит экстримально просто:
```java
@Override
public Stream<String> show(final Stream<Record> records) {
    return records.flatMap(this::show);
}
```

2019-04-21 10:52 UTC, DenisVerkhoturov commented on src/main/java/metamer/io/FileWriter.java
> +    private final String SP = System.getProperty("line.separator");
Тот же комментарий про взятие разделителя через вызов метода, вместо поиска строкой:
```java
System.lineSeparator()
```

2019-04-21 10:52 UTC, DenisVerkhoturov commented on src/main/java/metamer/io/FileWriter.java
> +                    bufferedWriter.write(str + SP);
Можно также использовать стандартный метод `BufferedWriter#newLine`, который записывает символ переноса строки, это позволит не объявлять лишнюю константу в рамках файла и избавит от конкотенации.
```java
bufferedWriter.write(str);
bufferedWriter.newLine();
```

2019-04-21 10:52 UTC, DenisVerkhoturov commented on src/main/java/metamer/io/FileWriter.java
> +            lines.forEach((str) -> {
Наряду с негласным правилом именовать методы возвращающие `Stream` чего-то названием этого типа во множественном числе (как и с массивами, кстати сказать), существует такое же правило именовать отдельные объекты при обработке этого множества существительным в единственном числе.
Информация о типе в этом конкретном случае нам не очень помогает, но в остальном правилу все еще можно следовать:
```java
lines.forEach(line -> { /* do something with line */ });
```

2019-04-21 10:52 UTC, DenisVerkhoturov commented on src/test/java/metamer/fastq/FastQTest.java
> +                new FastQ(resource(this.getClass(), "test.fastq")));
Парсер для `FastQ` делается точно так же, как парсер для `Fasta`, то есть никаких путей не принимает, инициализируется без параметров:
```java
Reader<Record> reader = new FileReader<>(resource(this.getClass(), "test.fastq"), FastQ.parser());
```

2019-04-21 10:53 UTC, DenisVerkhoturov commented
![](https://github.trello.services/images/mini-trello-icon.png) [Приложение должно уметь работать как с `fastq` так и с `fasta` в качестве входного файла.](https://trello.com/c/8NQ8cwdj/35-%D0%BF%D1%80%D0%B8%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B4%D0%BE%D0%BB%D0%B6%D0%BD%D0%BE-%D1%83%D0%BC%D0%B5%D1%82%D1%8C-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0%D1%82%D1%8C-%D0%BA%D0%B0%D0%BA-%D1%81-fastq-%D1%82%D0%B0%D0%BA-%D0%B8-%D1%81-fasta-%D0%B2-%D0%BA%D0%B0%D1%87%D0%B5%D1%81%D1%82%D0%B2%D0%B5-%D0%B2%D1%85%D0%BE%D0%B4%D0%BD%D0%BE%D0%B3%D0%BE-%D1%84%D0%B0%D0%B9%D0%BB%D0%B0)

2019-04-23 06:41 UTC, DenisVerkhoturov approved these changes

2019-04-23 06:41 UTC, merged