Functional tests
DenisVerkhoturov/metamer pull request #25
Opened 2019-04-20 22:01 UTC by ShapovalovaIrina

2019-04-20 22:04 UTC, ShapovalovaIrina commented on src/test/java/metamer/functional_tests/FunctionalTest.java
> +        if (!inputPath.toFile().setReadable(false)) {
У меня в этом месте возникла проблема, что входной файл не удавалось сделать недоступным для чтения. Но в теории, если бы он таким был, то тест должен нормально проходить

2019-04-21 09:30 UTC, DenisVerkhoturov requested changes
Спасибо, ты все поняла правильно! :+1: 

Ниже ты можешь найти рекомендации по тому, что хотелось доработать :wink:

2019-04-21 09:30 UTC, DenisVerkhoturov commented on src/test/java/metamer/functional_tests/FunctionalTest.java
> +    }
Перенеси, пожалуйста, `AfterAll` перед всеми тестами, обычно структура такая:
- `BeforeAll`
- `BeforeEach`
- `AfterEach`
- `AfterAll`
- все тесты

Так ты понимаешь какая логика оборачивается вокруг каждого теста раньше, чем начинаешь их читать.

2019-04-21 09:30 UTC, DenisVerkhoturov commented on src/test/java/metamer/functional_tests/FunctionalTest.java
> +            "-- HELP --" + newLine;
Жаль, что в `java` нет мультилайн текста, конечно, поэтому для подобных штук, я давно хотел предложить написать утилитный метод. Вынести его в какой-нибудь `Strings`, например, чтобы он помагал нам человеко-читаемо описывать такие штуки:
```java
import static metamer.utils.Strings.multiline;

multiline(
    "usage: java metamer.jar [-c <arg>] [-f <arg>] [-h]",
    "Options",
    "   -c,--command <arg>      Which command to do",
    "   -f,--filepath <arg>     Path to file",
    "   -h,--help               Present help"
)
```

Реализацию оставляю на твое усмотрение, напомню лишь, что для неопределенного количества аргументов мы используем `vararg` синтаксис:
```java
String multiline(final String... lines)
```

2019-04-21 09:30 UTC, DenisVerkhoturov commented on src/test/java/metamer/functional_tests/FunctionalTest.java
> +        assertThat(outputPath.toFile().exists(), is(true));
Чтобы вот такие штуки тоже были более эксплицитными, можно апдейтнуть нашу библиотеку матчеров:
```diff
--- a/build.gradle
+++ b/build.gradle
@@ -34,7 +34,7 @@ dependencies {
     compile 'commons-cli:commons-cli:1.4'
     compile 'io.vavr:vavr:0.9.3'
     testImplementation 'org.junit.jupiter:junit-jupiter-api:5.3.1'
-    testImplementation 'org.hamcrest:hamcrest-all:1.3'
+    testImplementation 'org.hamcrest:java-hamcrest:2.0.0.0'
     testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.3.1'
 }
```

Тaм есть `io`-матчеры, например, тут нам пригодился бы:
```java
import static org.hamcrest.io.FileMatchers.anExistingFile;

assertThat(outputPath.toFile(), anExistingFile());
```
При этом все матчеры, которые мы уже используем остаются так же на местах, то есть нам ничего не сломает этот апдейт, сплошные плюсы=)

Дополнительно почитать можно тут: [Baeldung: Hamcrest File Matchers](https://www.baeldung.com/hamcrest-file-matchers).

2019-04-21 09:30 UTC, DenisVerkhoturov commented on src/test/java/metamer/functional_tests/FunctionalTest.java
> +        if (!inputPath.toFile().setReadable(false)) {
Каждый отдельный тест должен быть изолированным и не делать ничего, что могло бы повлиять на прохождение других тестов. Поэтому подход с тестированием на примере одного единственного пути, и приведении этого пути в каждом тесте под нужды теста, а потом возвращание его в изначальное состояние - это подход, который обязательно приведет к проблемам.

Перепиши, пожалуйста, так, чтобы каждый тест, создавал себе сам все окружение, которое ему необходимо (файлы с нужными характеристиками доступа и контентом).

Пример создания файла, у на который вообще нет ни у кого прав ни чтение ни на письмо: [`createTempFile("inaccessible", "", asFileAttribute(fromString("---------")))`](https://github.com/DenisVerkhoturov/metamer/pull/18/files#diff-09d9f296a3ab5732af6ecd641ffa4373R38)

#### NB
1) Можно добавить одну небольшую оговорку - можно выносить какие-то вещи, которые используются во многих тестах, в скоуп класса, но только если эти штуки используются только "для чтения". То есть мы их никогда никак не меняем.

2) В рамках этого же комментария, будет уместно заметить, что нужно уходить от использования подготовленных тестовых файлов в `src/test/resources` (тут надо еще магически привлечь внимание @AnBrusn и @Sonik-zirael). Это плохой подход, люди думают, что сокращают время тестов таким образом, но это попытка решить другую проблему на самом деле - это значит, что архетектуру уже так завязали, что честные и чистые `unit`-тесты* в ней уже не написать. Это довольно большая тема, тут довольно много нужно написать, чтобы показать, что я имею ввиду и обосноватьмою позицию. Хотя так же справедливо будет сказать, что в `java` разработке так, конечно, делают постоянно.

\* если тест использует файловую систему - он уже ни разу не "честный чистый `unit`-тест", так как тестирует он уже не только логику юнита, но и работу файловой системы. То есть можно "уронить" его при абсолютно коректной реализации `unit`-а.

2019-04-21 09:30 UTC, DenisVerkhoturov commented on src/test/resources/metamer/functional_tests/inp.fasta
> +
Соответственно учитывая вышесказанное, я попрошу тебя удалить этот файл, и заменить его созданием нового временного файла с этим контентом:
```java
final Path path = Files.createTempFile("awesome", "fasta");
Files.write(path, List.of(
    ">id0 test",
    "ABCDEA",
    ">id1 test",
    "DEAB"
));
```

Ну или если контент у нас будет где-то еще использоваться, то мы можем сделать так:
```java
import metamer.utils.Strings.multiline;
/* ... */
final String content = multiline(
    ">id0 test",
    "ABCDEA",
    ">id1 test",
    "DEAB"
);
/* ... */
final Path path = Files.createTempFile("awesome", "fasta");
Files.write(path, content.getBytes());
```
```

2019-04-21 09:30 UTC, DenisVerkhoturov commented on src/test/java/metamer/functional_tests/FunctionalTest.java
> +    private final String newLine = System.getProperty("line.separator");
Это абсолютно валидный  способ взять системный разделитель строк, но в таком способе есть один недостаток - можно ведь опечататься и получить ошибку. Лучше брать его так:
```java
System.lineSeparator()
```

2019-04-21 09:30 UTC, DenisVerkhoturov commented on src/test/java/metamer/functional_tests/FunctionalTest.java
> +            "   -f,--filepath <arg>     Path to file" + newLine +
К этой задаче не очень имеет отношение, но у нас параметры, будут другими=) 
Во первых, `command` для нас не очень имеет смысл, потому что она у нас всего одна - собрать геном, другие вещи мы делать не умеем, а все остальное - просто опции того как именно мы это делаем.
Во вторых, `filepath`, тоже не имеет смысла в нашем случае, нам нужно будет читать их в аргументов а не параметров.

2019-04-21 09:30 UTC, DenisVerkhoturov commented on src/test/java/metamer/functional_tests/FunctionalTest.java
> +        assertThat(testOut.toString(), is(usage + usage));
Разнеси, пожалуйста, это на два отдельных теста. Хорошая практика следовать такому правилу: каждый тест проверяет только что-нибудь одно. Можно было бы сократить его до "один тест - один assert", но это уже не совсем правда. Иногда у нас комплексное состояние, и мы хотим проверить, что результат соответствует сразу нескольким требованиям. Например, что в результате:
1) создался файл
2) у него определенные характеристики доступа
2) файл имеет контент такой-то

Или, например, что в результате мы получили список:
1) с размером таким-то
2) состоящий из таких-то элементов

Здесь же, у нас тестируется не один результат на соответствие нескольким требованиям, а разные результаты на соответствие одному требованию.

2019-04-21 09:30 UTC, DenisVerkhoturov commented on src/test/java/metamer/functional_tests/FunctionalTest.java
> +        CliHandler.main("-stdin", "-stdout");
Я напоминаю, что у нас есть `wiki` страничка про то как использовать наше приложение: [Usage](https://github.com/DenisVerkhoturov/metamer/wiki/Usage).

@ShapovalovaIrina, @Sonik-zirael, @AnBrusn также всячески призываю всех присоединяться к обсуждению в контексте соответствующей задачи в `trello`: [[Обсуждение] Контракт приложения](https://trello.com/c/xIHnZSlQ/40-%D0%BE%D0%B1%D1%81%D1%83%D0%B6%D0%B4%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BA%D0%BE%D0%BD%D1%82%D1%80%D0%B0%D0%BA%D1%82-%D0%BF%D1%80%D0%B8%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D1%8F)

2019-04-21 09:31 UTC, DenisVerkhoturov commented on src/test/java/metamer/functional_tests/FunctionalTest.java
> +        if (!inputPath.toFile().setReadable(false)) {
Постарался ответить на это в рамках ревью [в этом комментарии](https://github.com/DenisVerkhoturov/metamer/pull/25#discussion_r277159449).

2019-04-21 09:31 UTC, DenisVerkhoturov commented
![](https://github.trello.services/images/mini-trello-icon.png) [Написать сквозные функциональные тесты для приложения](https://trello.com/c/zVG9ivkK/37-%D0%BD%D0%B0%D0%BF%D0%B8%D1%81%D0%B0%D1%82%D1%8C-%D1%81%D0%BA%D0%B2%D0%BE%D0%B7%D0%BD%D1%8B%D0%B5-%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%BE%D0%BD%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D0%B5-%D1%82%D0%B5%D1%81%D1%82%D1%8B-%D0%B4%D0%BB%D1%8F-%D0%BF%D1%80%D0%B8%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D1%8F)

2019-04-21 16:03 UTC, DenisVerkhoturov requested changes
Спасибо, очень оперативно внесла правки! :+1: 

У меня есть еще парочка просьб, кроме перечисленных ниже, не могла бы ты также сосквошить коммиты (помни про содержательное название) и убедиться, что все наши проверки качества проходят.

2019-04-21 16:03 UTC, DenisVerkhoturov commented on src/main/java/metamer/utils/Strings.java
> +        return tmpStr.toString();
Да, так тоже можно, а можно еще проще:
```java
import static java.util.Arrays.stream;
import static java.util.stream.Collectors.joining;
/* ... */
public static String multiline(final String... lines) {
    return stream(lines).collect(joining(newLine, "", newLine));
}
```
Контракт `Collectors#joining(String, String, String)`:
- `delimiter` - the delimiter to be used between each element
- `prefix` - the sequence of characters to be used at the beginning of the joined result
- `suffix` - the sequence of characters to be used at the end
               of the joined result

2019-04-21 16:03 UTC, DenisVerkhoturov commented on src/test/java/metamer/cmdparser/CliHandlerTest.java
> +        final Path outputPath = Files.createTempFile("out", ".fasta");
Удали, пожалуйста, этот тест из этого класса полностью. Как я и говорил, мы будем стремиться к разделению `unit`-тестов и функциональных. К тому же в твоем наборе тестов уже итак есть тест, который проверяет ровно это все=)

2019-04-21 16:03 UTC, DenisVerkhoturov commented on src/test/java/metamer/functional/tests/FunctionalTest.java
> +        outputPath.toFile().delete();
Я бы предложил вынести создание в отдельные функции, и сразу еще пометил бы файлы на удаление, чтобы после тестов они изчезли из системы:
```java
private static Path temporaryFile(final String name, final String suffix, final FileAttribute... attributes)
        throws IOException {
    final Path outputPath = Files.createTempFile(name, suffix, attributes);
    outputPath.toFile().deleteOnExit();
    return outputPath;
}

private static Path temporaryDirectory(final String name, final FileAttribute... attributes) throws IOException {
    final Path outputPath = Files.createTempDirectory(name, attributes);
    outputPath.toFile().deleteOnExit();
    return outputPath;
}
```
А `delete` в каждом тесте нам не нужен=)

2019-04-21 16:03 UTC, DenisVerkhoturov commented on src/main/java/metamer/cmdparser/CliHandler.java
>              outFilePath.toFile().createNewFile();
Из-за этой строчки, код который находится ниже не выполниться. В смысле, ниже мы проверяем можно ли писать по этому пути, но в этой строчке случиться `Exception` если это действительно так. Смотрим контракт `File#createNewFile()`:
>  @throws  SecurityException
    If a security manager exists and its {@linkjava.lang.SecurityManager#checkWrite(java.lang.String)} method denies write access to the file

Создавать файл в этом месте логики нет смысла, не могла бы ты удалить это действие, вместо этого мы будем создавать файл только при записи в него уже готового результата.

2019-04-21 16:03 UTC, DenisVerkhoturov commented on src/main/java/metamer/cmdparser/CliHandler.java
> +                System.out.println(outFilePath.toString() + Messages.FILE_IS_NOT_READABLE);
Ох уж эта копипаста=) Ты, нверное, имела ввиду `FILE_IS_NOT_WRITEBALE`:
```diff
--- a/src/main/java/metamer/cmdparser/CliHandler.java
+++ b/src/main/java/metamer/cmdparser/CliHandler.java
@@ -135,7 +135,7 @@ public class CliHandler {
             }
             outFilePath.toFile().createNewFile();
             if (!outFilePath.toFile().canWrite()) {
-                System.out.println(outFilePath.toString() + Messages.FILE_IS_NOT_READABLE);
+                System.out.println(outFilePath.toString() + Messages.FILE_IS_NOT_WRITABLE);
                 return;
             }
```
Один из тестов (`notWritableOutputFileTest`), к слову, не проходит сейчас ровно потому что сообщение не корректное, ну и потому, что выше есть создание файла, которое падает.

2019-04-21 16:03 UTC, DenisVerkhoturov commented on src/test/java/metamer/functional/tests/FunctionalTest.java
> +    public static void restoreStream() {
Поменяй, пожалуйста, на `AfterEach`, мало ли, может `junit` будет что-то писать между тестами, и мы потеряем этот вывод.

2019-04-21 16:03 UTC, DenisVerkhoturov commented on src/test/resources/metamer/functional/tests/inp.fasta
> +DEAB
Удали, пожалуйста, этот файл, мы ведь решили, что он нам не нужен.

2019-04-21 16:03 UTC, DenisVerkhoturov commented on src/test/java/metamer/functional/tests/FunctionalTest.java
> +        assertThat(Files.lines(outputPath).collect(toList()), contains(expected1, expected2));
А вот падение этого теста уже интересно, по логике, мы уже должны были проскачить этот шаг. Ок. Хорошо, что обнаружили, теперь, когда у нас есть тесты, будем лучше контролировать ситуацию=)

Пока пометь его, пожалуйста, аннотацией:
```java
@Disabled("To fix")
```

2019-04-21 16:03 UTC, DenisVerkhoturov commented on src/test/java/metamer/functional/tests/FunctionalTest.java
> +    public void writeInStdoutTest() throws IOException {
Пометь, пожалуйста, этот тест аннотацией:
```java
@Disabled("Writing to stdout is not implemented yet")
```

2019-04-21 16:03 UTC, DenisVerkhoturov commented on src/test/java/metamer/functional/tests/FunctionalTest.java
> +    public void readingFromStdinTest() throws IOException {
Пометь, пожалуйста, этот тест аннотацией:
```java
@Disabled("Reading from stdin is not implemented yet")
```

2019-04-21 16:03 UTC, DenisVerkhoturov commented on src/test/java/metamer/functional/tests/FunctionalTest.java
> +    public void readingFromStdinWriteInStdoutTest() {
Пометь, пожалуйста, этот тест аннотацией:
```java
@Disabled("Reading from stdin and writing to stdout are not implemented yet")
```

2019-04-21 21:44 UTC, DenisVerkhoturov approved these changes

2019-04-21 21:44 UTC, merged