Fix functional test
DenisVerkhoturov/metamer pull request #33
Opened 2019-04-29 19:12 UTC by Sonik-zirael

2019-04-29 19:18 UTC, Sonik-zirael commented on cli/src/main/java/metamer/cmdparser/CliHandler.java
> +            if (!outputPath.toFile().canWrite() && outputPath.toFile().exists()) {
У нас файл не создаётся в `CliHandler` , и это условие всегда выполнялось - так как если файл не существует, то и записать в него нельзя. По крайней мере, это показали эксперименты с тестом `notWritableOutputFileTest()` . 
Если создавать в нём файл просто как

`final Path outputPath = temporaryFile("inaccessible", ".fasta");
outputPath.toFile().delete();`

 то тест всё равно будет проходить, несмотря на то, что запрета на запись не было. 
Скорее всего придётся переписать этот тест ?

2019-04-29 21:38 UTC, DenisVerkhoturov requested changes
Отлично, очень оперативно нашла проблему! :+1:

2019-04-29 21:38 UTC, DenisVerkhoturov commented on functional_tests/src/test/java/functional/tests/FunctionalTest.java
> +        final String expected2 = "DEABC";
Немного на магию похоже, раз мы не очень уверы, как наш собственный ассемблер должен собирать геном=)
Исправление теста методом замены ожидаемого значения - плохой знак. К задаче в `trello` я прикрепил стихотворение, оно классическое, с большим колличеством повторений, поэтому должно хорошо лечь на нашу задачу. Поставь, пожалуйста, его в кажестве тестовых данных.

2019-04-29 21:38 UTC, DenisVerkhoturov commented on functional_tests/src/test/java/functional/tests/FunctionalTest.java
> -        outputPath.toFile().delete();
Да, ты права, что удаление фала здесь не нужно. Но это все еще не эмулирует ситуацию, в которой, мы проверяем, что адекватно сообщаем пользователю, что он указал путь, по которому не может писать. Разбей, пожалуйста, создание `outputPath` на две стадии:
- сначала мы создаем защищенную папку
- а потом говорим, что хотим записать файл в нее
```java
final Path inaccessible = temporaryDirectory("inaccessible", asFileAttribute(fromString("---------")));
final Path outputPath = inaccessible.resolve("out.fasta");
```
Тест начнет падать, и это правильно, потому что проверка в `CliHandler` (строка 150):
```java
if (!outputPath.toFile().canWrite() && outputPath.toFile().exists()) {
    System.out.println(outputPath.toString() + CliHandlerMessages.FILE_IS_NOT_WRITABLE);
    return;
}
```
Не делает то, что нужно. Она пытается брать на себя работу еще и проерки, которая располагается под ней - о том, что мы пытаемся перезаписать существующий файл. Исправить ее просто:
```java
if (!outputPath.toFile().canWrite()) {
    System.out.println(outputPath.toString() + CliHandlerMessages.FILE_IS_NOT_WRITABLE);
    return;
}
```

2019-04-30 08:58 UTC, DenisVerkhoturov commented
![](https://github.trello.services/images/mini-trello-icon.png) [Поправить базовую функциональность](https://trello.com/c/LX7VwuKW/62-%D0%BF%D0%BE%D0%BF%D1%80%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-%D0%B1%D0%B0%D0%B7%D0%BE%D0%B2%D1%83%D1%8E-%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%BE%D0%BD%D0%B0%D0%BB%D1%8C%D0%BD%D0%BE%D1%81%D1%82%D1%8C)

2019-05-01 07:11 UTC, Sonik-zirael commented on cli/src/main/java/metamer/cmdparser/CliHandler.java
> +                //return;
Мы говорили про закомментированный код, но тут эта строчка не даёт проходить тесту `correctInput` потому что мы создаём выходной файл гораздо позже этого момента,  а тут нас всё время выкидывает, так как файла нет - в него не записать

2019-05-01 18:33 UTC, DenisVerkhoturov requested changes
Спасибо, финальные правки и мержим! :+1: 

После этих изменений, подготовь, пожалуйста, пулл-реквест к мержу.

2019-05-01 18:33 UTC, DenisVerkhoturov commented on cli/src/main/java/metamer/cmdparser/CliHandler.java
> +                //return;
Да, понял в, чем поинт. В общем `return` мы возвращаем, а проверку самого файла заменяем на проверку директории, в которой он находится. Соответственно, если мы не можем писать в эту директорию, значит и файл мы там создать не сможем:
```java
if (!outputPath.getParent().toFile().canFrite()) /** ... */
```

2019-05-01 18:33 UTC, DenisVerkhoturov commented on cli/src/main/java/metamer/graph/GraphCycle.java
> +        tmpStr.insert(0, startCycle.kmer.substring(0, startCycle.kmer.length() - 2));
Не могу добавить комментарий к нужно строче, но это самая близкая к нужно строка. Удали, пожалуйста, запись в `stdout` выше, когда у нас нет цикла. Это совершенно не нужное действие, а еще оно ломает нам тесты сейчас.

2019-05-01 18:33 UTC, DenisVerkhoturov commented on functional_tests/src/test/java/functional/tests/RhymeTest.java
> +        final String expected2 = multiline(
Предлагаю не дублировать все стихотворение два раза в тесте, а вынести его в отдельную переменную. Записать можно, например, так:
```java
Files.write(inputPath, ">id 0 test\n".getBytes());
Files.write(inputPath, rhyme.getBytes(), StandardOpenOption.APPEND);
```

2019-05-01 18:33 UTC, DenisVerkhoturov commented on functional_tests/src/test/java/functional/tests/RhymeTest.java
> +package metamer.functional.tests;
Нашел еще одну проблемку, пакет теста указан один, а по факту он лежит в другом. Добавь, пожалуйста, папку `metamer` над `functional/tests`. Чтобы структура соответствовала указанному пакету. Тоже самое с сновным тестом в этом пакете.

2019-05-01 18:33 UTC, DenisVerkhoturov commented on functional_tests/src/test/java/functional/tests/RhymeTest.java
> +        inputPath.toFile().deleteOnExit();
Вынеси, пожалуйста, методы `temporaryFile` и `temproraryDirectory` в отдельный утилитный класс в тестах в этом модуле. И используй его здесь. Еще добавь, пожалуйста, к этому `temporaryPath`:
```java
public static Path temporaryPath(final String prefix, final String suffix) {
    return temporaryPath(Path.of(System.getProperty("java.io.tmpdir")), prefix, suffix);
}

public static Path temporaryPath(final Path parent, final String prefix, final String suffix) {
    final String random = Long.toUnsignedString(new SecureRandom().nextLong());
    final String name = prefix + random + suffix;
    final Path outputPath = parent.resolve(name);
    outputPath.toFile().deleteOnExit();
    return outputPath;
}
```
Он нам понадобится как тут и как минимум, еще в двух тестах `correctInputTest` и `readingFromStdinTest`. То есть всегда, когда создается `temporaryFile` и затем затем сразу удаляется. Вместо этого нам ведь просто нужен путь.

2019-05-02 10:38 UTC, DenisVerkhoturov requested changes

2019-05-02 10:38 UTC, DenisVerkhoturov commented on functional_tests/src/test/java/metamer/functional/tests/RhymeTest.java
> +    }
Зачем объявлять здесь точно такую же функцию, какая у нас уже есть в утилитах? Замени, пожалуйста, на использование функции из ` functional_tests/src/test/java/metamer/functional/tests/Utils.java`.

2019-05-02 10:38 UTC, DenisVerkhoturov commented on functional_tests/src/test/java/metamer/functional/tests/RhymeTest.java
> +        outputPath.toFile().delete();
Нет необходимости создавать файл и сразу его удалять, у нас ведь есть функция в ` functional_tests/src/test/java/metamer/functional/tests/Utils.java`, которая просто создает временный путь - это ровно то, что нам нужно.

2019-05-02 12:34 UTC, DenisVerkhoturov approved these changes

2019-05-02 12:34 UTC, merged