Fix pitest
DenisVerkhoturov/metamer pull request #34
Opened 2019-04-29 20:40 UTC by ShapovalovaIrina

2019-04-29 21:53 UTC, DenisVerkhoturov requested changes
Огонь, очень быстро нашла проблему! :+1:

2019-04-29 21:53 UTC, DenisVerkhoturov commented on build.gradle
> -        mutators = ['ALL']
Не понимаю необходимости отключать все мутаторы, вроде и с ними данный фикс все чинит?

2019-04-29 21:53 UTC, DenisVerkhoturov commented on build.gradle
> +        testSourceSets = [project.sourceSets.test, project(':cli').sourceSets.test]
Исключи, пожалуйста, исходники относящиеся к функциональным тестам (`project.sourceSets.{main, test}`), потому, что они должны быть полностью отдельно, и не должны участвовать в подсчете покрытия.

2019-04-30 06:56 UTC, ShapovalovaIrina commented on build.gradle
> -        mutators = ['ALL']
Ой, я видимо просто случайно удалила эту строчку и не заметила... В новом коммите все верну

2019-04-30 08:14 UTC, DenisVerkhoturov approved these changes

2019-04-30 08:14 UTC, merged

2019-04-30 08:15 UTC, DenisVerkhoturov commented
![](https://github.trello.services/images/mini-trello-icon.png) [pitest не проходит даже локально](https://trello.com/c/OZcTXzs7/61-pitest-%D0%BD%D0%B5-%D0%BF%D1%80%D0%BE%D1%85%D0%BE%D0%B4%D0%B8%D1%82-%D0%B4%D0%B0%D0%B6%D0%B5-%D0%BB%D0%BE%D0%BA%D0%B0%D0%BB%D1%8C%D0%BD%D0%BE)