Pipeline
DenisVerkhoturov/metamer pull request #35
Opened 2019-05-04 12:05 UTC by AnBrusn

Команды вроде такой: cat reads.fasta | java -jar metamer.jar --fasta | tee assembled.fasta выполняются хорошо. А с тестами что-то странное. Если запускать readingFromStdinWriteInStdoutTest, readingFromStdinTest или writeInStdoutTest по отдельности, то они проходят. А если запускать сразу все функциональные тесты, то эти три падают.

2019-05-06 15:22 UTC, alex-klimina commented
> 
> 
> Команды вроде такой: cat reads.fasta | java -jar metamer.jar --fasta | tee assembled.fasta выполняются хорошо. А с тестами что-то странное. Если запускать readingFromStdinWriteInStdoutTest, readingFromStdinTest или writeInStdoutTest по отдельности, то они проходят. А если запускать сразу все функциональные тесты, то эти три падают.

К сожалению, не могу запустить сейчас тесты и посмотреть точнее, но вижу, что переменная

2019-05-06 16:21 UTC, DenisVerkhoturov commented
![](https://github.trello.services/images/mini-trello-icon.png) [Приложение должно уметь работать в режиме пайплайна](https://trello.com/c/qmt74IzU/39-%D0%BF%D1%80%D0%B8%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B4%D0%BE%D0%BB%D0%B6%D0%BD%D0%BE-%D1%83%D0%BC%D0%B5%D1%82%D1%8C-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0%D1%82%D1%8C-%D0%B2-%D1%80%D0%B5%D0%B6%D0%B8%D0%BC%D0%B5-%D0%BF%D0%B0%D0%B9%D0%BF%D0%BB%D0%B0%D0%B9%D0%BD%D0%B0)

2019-05-06 22:48 UTC, DenisVerkhoturov requested changes
Сейчас я думаю, что логичнее было бы сначала сделать [таску про абстракции над источниками и целями](https://trello.com/c/syGHWZ09/64-%D0%B0%D0%B1%D1%81%D1%82%D1%80%D0%B0%D0%BA%D1%86%D0%B8%D1%8F-%D0%BD%D0%B0%D0%B4-%D0%B8%D1%81%D1%82%D0%BE%D1%87%D0%BD%D0%B8%D0%BA%D0%BE%D0%BC-%D1%80%D0%B8%D0%B4%D0%BE%D0%B2-%D0%B8-%D1%86%D0%B5%D0%BB%D1%8C%D1%8E-%D0%BA%D0%BE%D0%BD%D1%82%D0%B8%D0%B3%D0%BE%D0%B2), так как текущая таска фактически зависит от нее. Ты могла бы переключиться на нее, а потом вернуться к этой задаче?

2019-05-06 22:48 UTC, DenisVerkhoturov commented on functional_tests/src/test/java/metamer/functional/tests/FunctionalTest.java
> +        final String expected1 = ">cycle from file: " + null;
Не нравиться мне вот, как у нас генерируется идентификатор для контигов. Особенно магически там `null` видеть! 🤨

Поставлю таску на будущее, в рамках которой нужно будет подписывать контиги идентификаторами вида `seq1`, `seq2`, `seq3`...

2019-05-12 21:13 UTC, DenisVerkhoturov commented
Спасибо, все огонь! :+1: 
Изменения вмержены руками, поэтому сам пулл-реквест закрываем.

2019-05-12 21:13 UTC, closed without merging