Lazy parsing
DenisVerkhoturov/metamer pull request #37
Opened 2019-05-06 17:28 UTC by ShapovalovaIrina

2019-05-06 18:00 UTC, DenisVerkhoturov commented
![](https://github.trello.services/images/mini-trello-icon.png) [Ленивый парсинг](https://trello.com/c/g9GVHA65/60-%D0%BB%D0%B5%D0%BD%D0%B8%D0%B2%D1%8B%D0%B9-%D0%BF%D0%B0%D1%80%D1%81%D0%B8%D0%BD%D0%B3)

2019-05-06 19:45 UTC, DenisVerkhoturov requested changes
Отлично! :+1: 

Ты все поняла верно, осталось доделать совсем немного, но ключевое=)

2019-05-06 19:45 UTC, DenisVerkhoturov commented on cli/src/main/java/metamer/utils/SplitBefore.java
> +public class SplitBefore<T> implements Iterator<T> {
`SplitBefore<T>` должен наследоваться от `Iterator<List<T>>`. Соответственно метод `next` будет возвращать не `T`, а `List<T>`.

\* обновил описание задачи по этому поводу

2019-05-06 19:45 UTC, DenisVerkhoturov commented on cli/src/main/java/metamer/utils/SplitBefore.java
> +    T delimeter;
Спрячь, пожалуйста, поля `downstream` и `delimiter` от внешнего пользователя, и сделай их иммутабельными.

2019-05-06 19:45 UTC, DenisVerkhoturov commented on cli/src/main/java/metamer/utils/Splitter.java
> +            }
Все верно, здесь мы просто возвращаем экземпляр `SplitBefore`. В области видимости у нас все для этого есть: и `iterator`, который нам передадут непосредственно, и `delimiter` через замыкание тоже нам доступен.
```java
return new Splitter<T>() {
    @Override
    public Iterator<List<T>> apply(final Iterator<T> iterator) {
        return new SplitBefore<>(iterator, delimiter);
    }
};
```

И еще один полезный момент, мы можем заменить аннонимный класс лямбдой и получить минимум сервисного кода, только чистую логику:
```java
return iterator -> new SplitBefore<>(iterator, delimiter);
```

И на этом работа в `Splitter` окончена=)

2019-05-06 19:45 UTC, DenisVerkhoturov commented on cli/src/main/java/metamer/utils/Splitter.java
> +    Iterator<List<T>> apply(Iterator<T> tIterator);
Переопределять без реализации - избыточно, а в качестве абстрактного метода - мы итак наследуем его от родительского интерфейса.

2019-05-06 19:45 UTC, DenisVerkhoturov commented on cli/src/main/java/metamer/utils/Streams.java
> +    };
Вот здесь может быть немного сложно, я не хочу чтобы ты тратила много времени на поиски, поэтому я просто прямо скажу что тут должно быть:
```java
import java.util.Iterator;
import java.util.Spliterator;
import java.util.Spliterators;
import java.util.stream.StreamSupport;
import static java.util.Spliterator.SIZED;
import static java.util.Spliterator.SORTED;
import static java.util.Spliterator.SUBSIZED;
/* ... */
public static <T> Stream<List<T>> chunks(final Splitter<T> splitter, final Stream<T> source) {
    final Spliterator<T> sourceSpliterator = source.spliterator();
    final Iterator<T> sourceIterator = Spliterators.iterator(sourceSpliterator);
    final Iterator<List<T>> iterator = splitter.apply(sourceIterator);
    final int characteristics = sourceSpliterator.characteristics() & ~(SIZED | SUBSIZED | SORTED);
    final Spliterator<List<T>> spliterator = Spliterators.spliterator(iterator, -1, characteristics);
    return StreamSupport.stream(spliterator, false);
}
```

По существу, все что осталось реализовать (хотя это в тоже время самая сложная часть) - это как раз методы `SplitBefore#hasNext()` и `SplitBefore#next()`.

2019-05-06 19:45 UTC, DenisVerkhoturov commented on cli/src/main/java/metamer/utils/SplitBefore.java
> +        this.delimeter = delimeter;
Давай еще немного обобщим, так будет проще, а главное логичнее. Вместо `T`, `splitBefore` должен принимать `java.util.function.Predicate<T>` в качестве `delimiter`.

Тогда внешний пользователь может вызывать нас так:
```java
final Stream<List<String>> chunks = Streams.chunks(splitBefore(line -> line.startsWith(">")), lines);
```

А в самом итераре при наборе следующего элемента мы сможем использовать это так:
```java
final T item = downstream.next();
if (delimiter.test(item)) /* Have met delimiter can return next element now */
else /* Haven't met delimiter yet */
```
Только помни также о том, что нужно еще следить за тем, что в `downstream` итераторе еще есть элементы, если нет, то заканчиваем и возвращаем, что накопилось.

2019-05-06 19:45 UTC, DenisVerkhoturov commented on cli/src/main/java/metamer/utils/Streams.java
> +    public static Stream<String> windows(final String str, final int size) {
Перенеси, пожалуйста, метод `windows` в утилитный класс `Strings`. Так будет логичнее, он же только со строками работает=)

2019-05-08 17:42 UTC, ShapovalovaIrina commented on cli/src/test/java/metamer/utils/SplitBeforeTest.java
> +        assertThat(spl.next(), is(List.of("<id2", "ABCD2")));
Написала примерные тесты, чтобы проверить то, как работают наши функции
И проблема в том, что после первого вызова _spl.next()_ итератор перемещается на строку _"ABCD2"_, так как мы исследовали _"<id2"_ на наличие разделителя. При первом вызове spl.next() все в порядке, а потом уже проблемы...

2019-05-08 17:45 UTC, ShapovalovaIrina commented on cli/src/main/java/metamer/utils/SplitBefore.java
> +    SplitBefore(final SplitBefore<T> splitBefore) {
Тут была мысль сделать конструктор копирования для объекта типа SplitBefore<T>. Новый объект действительно имеет другой адрес, но все равно указывает на один и тот же итератор delimiter
Пыталась создать копию итератора, но не получилось

2019-05-09 00:12 UTC, DenisVerkhoturov requested changes

2019-05-09 00:12 UTC, DenisVerkhoturov commented on cli/src/main/java/metamer/utils/SplitBefore.java
> +    SplitBefore(final SplitBefore<T> splitBefore) {
Конструктор копирования нам не поможет в нашей ситуации, если често, не понимаю в чем была задумка, что предполагалось им решить?=)

2019-05-09 00:12 UTC, DenisVerkhoturov commented on cli/src/main/java/metamer/utils/SplitBefore.java
> +        return false;
Реализация `hasNext` на самом деле сводится к вызову `downstream.hasNext()` хотя и с определенной добавкой, которая будет покрывать случай, когда у нас последний `downstream.next()` был разделителем.

2019-05-09 00:12 UTC, DenisVerkhoturov commented on cli/src/main/java/metamer/utils/SplitBefore.java
> +            if (iteratorValue.toString().indexOf(delimeter.toString()) == 0 && delimiterPresent) {
Вот тут вообщем-то самая непростая логика скрывается. То, что я очень люблю, но на чем строиться вся суть паттерна `Iterator` - мутируемое состояние (хорошо, что оно по крайней мере внутреннее).

Не забудь в конце теста после проверки, что все элементы получены в нужном порядке, в итераторе больше нет ничего:
```java
final Iterator<Character> iterator = Iterator.of('|', '|', 'a', '|', 'a', 'b', '|', 'a', 'b', 'c');
final SplitBefore<Character> chunks = new SplitBefore<>(iterator, '|');
assertThat(chunks.next(), is(List.of('|')));
assertThat(chunks.next(), is(List.of('|', 'a')));
assertThat(chunks.next(), is(List.of('|', 'a', 'b')));
assertThat(chunks.next(), is(List.of('|', 'a', 'b', 'c')));
assertThat(chunks.hasNext(), is(false));
```

Так же стоит выделить следующие граничные случаи (`|` - делимитер):

| Downstream | SplitBefore |
|----------------:|:---------------|
| `[ ]` | `[ ]` |
| `['a']` | `[['a']]` |
| `['\|']`  | `[['\|']]`  |
| `['\|', 'a']` | `[['\|', 'a']]` |
| `['a', '\|']` | `[['a'], ['\|']]` |

Попробуй решить сама, но если не будет получаться ниже под спойлерами приведены варианты реализации. Помни также [комментарий, который я оставлял про `predicare`](https://github.com/DenisVerkhoturov/metamer/pull/37#discussion_r281329839).

<details>
<summary>Спойлер - решение</summary>

```java
package metamer.utils;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.NoSuchElementException;

public class SplitBefore<T> implements Iterator<List<T>> {
    private final Iterator<T> downstream;
    private final T delimiter;
    private T cursor;

    SplitBefore(final Iterator<T> downstream, final T delimiter) {
        this.downstream = downstream;
        this.delimiter = delimiter;
    }

    @Override
    public boolean hasNext() {
        return downstream.hasNext() || cursor != null;
    }

    @Override
    public List<T> next() {
        if (!hasNext()) throw new NoSuchElementException();

        final List<T> list = new ArrayList<>();

        if (cursor != null) {
            list.add(cursor);
            cursor = null;
        }

        while (downstream.hasNext()) {
            cursor = downstream.next();
            if (delimiter.equals(cursor)) break;
            list.add(cursor);
            cursor = null;
        }

        return list.isEmpty() && hasNext() ? next() : list;
    }
}
```

</details>


<details>
<summary>Спойлер - `Predicate` в качестве делителя</summary>

```java
package metamer.utils;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.NoSuchElementException;
import java.util.function.Predicate;

public class SplitBefore<T> implements Iterator<List<T>> {
    private final Iterator<T> downstream;
    private final Predicate<T> delimiter;
    private T cursor;

    SplitBefore(final Iterator<T> downstream, final Predicate<T> delimiter) {
        this.downstream = downstream;
        this.delimiter = delimiter;
    }

    @Override
    public boolean hasNext() {
        return downstream.hasNext() || cursor != null;
    }

    @Override
    public List<T> next() {
        if (!hasNext()) throw new NoSuchElementException();

        final List<T> list = new ArrayList<>();

        if (cursor != null) {
            list.add(cursor);
            cursor = null;
        }

        while (downstream.hasNext()) {
            cursor = downstream.next();
            if (delimiter.test(cursor)) break;
            list.add(cursor);
            cursor = null;
        }

        return list.isEmpty() && hasNext() ? next() : list;
    }
}
```

</details>

2019-05-09 00:14 UTC, DenisVerkhoturov commented on cli/src/test/java/metamer/utils/SplitBeforeTest.java
> +        assertThat(spl.next(), is(List.of("<id2", "ABCD2")));
Нам необходимо помнить последний исследованный `downstream.next()` между вызовами нашего `next()`, и собственно новый список начинать с него при вызове.

2019-05-09 00:18 UTC, DenisVerkhoturov commented on cli/src/main/java/metamer/utils/SplitBefore.java
> +            if (iteratorValue.toString().indexOf(delimeter.toString()) == 0 && delimiterPresent) {
Аа, да, собственно для работы с предикатов в качестве разделителя, мы будем инстанцировать наш `Splitter`, например, так:
```java
new SplitBefore<>(iterator, symbol -> symbol == '|')
```

2019-05-12 17:36 UTC, DenisVerkhoturov approved these changes

2019-05-12 17:38 UTC, DenisVerkhoturov commented
Спасибо, все огонь! :+1:
Изменения вмержены руками, поэтому сам пулл-реквест закрываем.

2019-05-12 17:38 UTC, closed without merging