Typed errors
DenisVerkhoturov/metamer pull request #41
Opened 2019-05-17 18:36 UTC by ShapovalovaIrina

2019-05-17 18:42 UTC, ShapovalovaIrina commented on cli/src/main/java/metamer/cmdparser/CliHandler.java
Тут у меня возникла небольшая трудность 
До введения исключений в качестве Either.left мы возвращали Seq<String>, а сейчас нужно Exception. Но дело в том, что тут у нас есть строчка return Either.left(usage), которая возвращает String...
И пока что есть вариант либо сразу же выводить в stdout usage, либо в validation в качестве invalid возращать exception().getMessage(), то есть String. Хотя как я поняла, последний вариант не подойдет, потому что мы хотим вернуть саму ошибку

2019-05-17 18:51 UTC, ShapovalovaIrina commented on cli/src/main/java/metamer/cmdparser/exception/NoFilePath.java
> +public class NoFilePath extends Exception {
И хотелось бы небольшое уточнение по данному типу ошибок
Тут пока не делала никаких полей с данными, как обычно в других ошибках (например, private final Path path), потому что тут мы сообщаем об отсутствии конкретного аргумента
Но может стоит хранить String[] args, то есть все переданные ключи и аргументы командной строки? Или это будет излишним?

2019-05-18 11:13 UTC, DenisVerkhoturov requested changes
Отлично, осталось еще с тестами разобраться! :+1:

2019-05-18 11:13 UTC, DenisVerkhoturov commented on cli/src/main/java/metamer/cmdparser/CliHandler.java
Да, тут нам нужно немного изменить подход. Я предлагаю подходить к проблеме так -  `parse` пытается построить команду для выполнения. Соответственно поменять, то что он возвращает нужно на `Runnable`:
```diff
--- a/cli/src/main/java/metamer/cmdparser/CliHandler.java
+++ b/cli/src/main/java/metamer/cmdparser/CliHandler.java
@@ -1,5 +1,6 @@
 package metamer.cmdparser;
 
+import io.vavr.API;
 import io.vavr.collection.List;
 import io.vavr.collection.Seq;
 import io.vavr.control.Either;
@@ -57,20 +58,19 @@ public class CliHandler {
         try {
             Match(parse(args)).of(
                     Case($Left($()), messages -> run(() -> messages.forEach(System.out::println))),
-                    Case($Right($()), assembler -> run(assembler::assemble))
+                    Case($Right($()), API::run)
             );
         } catch (final ParseException exp) {
             System.out.println(exp.getMessage());
         }
     }
 
-    public static Either<Seq<String>, Assembler> parse(final String[] args) throws ParseException {
+    public static Either<Seq<Exception>, Runnable> parse(final String[] args) throws ParseException {
         final CommandLineParser parser = new DefaultParser();
         final CommandLine line = parser.parse(options, args);
 
         if (args.length == 0 || line.hasOption("help")) {
-            final List<String> usage = List.of(printHelp(options));
-            return Either.left(usage);
+            return Either.right(() -> System.out.println(printHelp(options)));
         }
 
         final String k = line.getOptionValue("k");
@@ -87,7 +87,7 @@ public class CliHandler {
             validation = validateFromStdToStd(k, format);
         }
 
-        return validation.toEither();
+        return validation.toEither().map(assembler -> assembler::assemble);
     }
```

2019-05-18 11:13 UTC, DenisVerkhoturov commented on cli/src/main/java/metamer/cmdparser/exception/NoFilePath.java
> +public class NoFilePath extends Exception {
Тут лучше обобщить вместе с `NoLength` и сделать ошибку, которая говорит, что значения для аргумента нет, например `NoValueForArgument`, которая в качестве поля содержит как раз, что не указано. Но вообще, у нас вроде как `ParseException` случиться, если указан, например, ключ `--input`, но после него нет значения. Потому что для этой опции у нас стоит - аргумент обязательно:
```java
/* options */ .addOption("i", "input", /* hasArg */ true, "Input file with reads to be analyzed")
```
А еще у нас есть тест, который это проверяет - `CliHandlerTest#nullInputPathTest`. И проверяет он это как раз так:
```java
assertThrows(ParseException.class, () -> CliHandler.parse(new String[] {"-k", "abc", "-f", "fasta", "-i"}));
```
Это по всей видимости так же значит, что мы можем во всех валидациях убрать ветку с проверкой на `null`=)

2019-05-18 20:17 UTC, DenisVerkhoturov approved these changes

2019-05-18 20:17 UTC, merged

2019-05-19 18:02 UTC, DenisVerkhoturov commented
![](https://github.trello.services/images/mini-trello-icon.png) [Типизированные ошибки](https://trello.com/c/ZCdPp0oA/66-%D1%82%D0%B8%D0%BF%D0%B8%D0%B7%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%BD%D1%8B%D0%B5-%D0%BE%D1%88%D0%B8%D0%B1%D0%BA%D0%B8)