Graph assemble
DenisVerkhoturov/metamer pull request #43
Opened 2019-05-20 16:24 UTC by Sonik-zirael

2019-05-22 11:22 UTC, DenisVerkhoturov commented
![](https://github.trello.services/images/mini-trello-icon.png) [Мы должны искать не цикл а все контиги в графе](https://trello.com/c/a9Lc4wZD/63-%D0%BC%D1%8B-%D0%B4%D0%BE%D0%BB%D0%B6%D0%BD%D1%8B-%D0%B8%D1%81%D0%BA%D0%B0%D1%82%D1%8C-%D0%BD%D0%B5-%D1%86%D0%B8%D0%BA%D0%BB-%D0%B0-%D0%B2%D1%81%D0%B5-%D0%BA%D0%BE%D0%BD%D1%82%D0%B8%D0%B3%D0%B8-%D0%B2-%D0%B3%D1%80%D0%B0%D1%84%D0%B5)

2019-05-22 14:25 UTC, DenisVerkhoturov requested changes
Знаю, что вы еще работаете, и еще не закончили, просто выдалась минутка, решил помочь=)

2019-05-22 14:25 UTC, DenisVerkhoturov commented on cli/src/main/java/metamer/assembler/Assembler.java
> +        writer.accept(list.stream());
Сборка в список излишня (кроме того выполнятся будет жадно), чтобы превратить стрим типа `A` в стрим типа `B` (лениво), нужно воспользоваться методом `map` и передать ему функцию, которая преобразовывает элемент типа `A` в элемент типа `B`. `map :: Stream<A> -> (A -> B) -> Stream<B>`. Например:
```java
final Stream<String> words = Stream.of("cat", "milk", "kitten");
assertThat(words.map(word -> word.length).collect(toList()), contains(3, 4, 6));
```
Соответственно мы это можем использовать так:
```java
final Stream<Record> contigs = graphCycle.findCycle().map(e -> new Record("seq", "", e));
writer.accept(contigs);
```

2019-05-22 14:25 UTC, DenisVerkhoturov commented on cli/src/main/java/metamer/graph/GraphCycle.java
>          for (final Map.Entry<String, Node> entry : graph.getNodes().entrySet()) {
Давайте расширим контракт класса `Graph` методами `nodes`, который возвращает все вершины в виде `Stream<Node>` и метода `edges`, который возвращает все ребра в виде `Stream<Edge>`. Соответственно сделаем класс `Edge`, который просто будет хранить две соединяемые вершины. Вершины мы уже итак храним, и тут ничего сложного в том, чтобы их вернуть не будет. А ребра будем собирать только по требованию.

Соответственно тут мы будем использовать этот способ получения вершин.

2019-05-22 14:25 UTC, DenisVerkhoturov commented on cli/src/main/java/metamer/graph/GraphCycle.java
>      private String createCycle() {
Похоже, что метод `createCycle` нигде не используется, значит, вероятно, лучше удалить.

2019-05-22 14:25 UTC, DenisVerkhoturov commented on cli/src/main/java/metamer/graph/GraphCycle.java
> +        });
Этот компаратор можно не объявлять самостоятельно, а определить в терминах уже существующих:
```java
import static java.util.Comparator.comparing;
/* ... */
contigs.sort(comparing(String::length));
```

К тому же стоит понимать, что сравнивать числа методом разности - это не безопасный способ, чтобы понять почему достаточно ответить на вопрос: "Что будет если из `Integer.MIN_VALUE` вычесть единицу?".

2019-05-22 14:25 UTC, DenisVerkhoturov commented on cli/src/main/java/metamer/assembler/Assembler.java
> +        stream.forEach(e -> list.add(new Record("seq", "", e)));
Если мы будем записывать все контиги с идентификатором `seq`, то это не будет уникальным идентификатором. Я предлагаю формировать идентификатор, по принципу `seqN`, где `N` это целое число от `1` и выше.

2019-05-25 19:03 UTC, Sonik-zirael commented on cli/src/main/java/metamer/assembler/Assembler.java
> +        stream.forEach(e -> list.add(new Record("seq", "", e)));
А мы можем, например, генерировать рандомное число в самом классе Record? А то тут мы не придумали, как увеличивать переменную при исполнении потока

2019-05-27 15:39 UTC, DenisVerkhoturov commented on cli/src/main/java/metamer/assembler/Assembler.java
> +        stream.forEach(e -> list.add(new Record("seq", "", e)));
Понимаю, в чем тут у вас загвоздка приключилась. Проблема в том, что все используемые в `lambda` переменные должны быть `effectively final`, так? И мы не можев `java` писать такой код:
```java
int counter = 0;
final Supplier<String> sayHello = () -> {
    counter += 1; // Не скомпилируется
    return "hello";
};
```
Но есть пара обходных путей, первый самый глупый и прямолинейный, я его не очень люблю, но он работает - использовать массив из одного элемента:
```java
final int[] counter = new int[] { 0 };
final Supplier<String> sayHello = () -> {
    counter[0] += 1; // Массив final, но его элементы мутабельны
    return "hello";
};
```
Другой способ - это сделать локальную обертку:
```java
class MutableHolder {
  int value;
}
final MutableHolder counter = new MutableHolder();
final Supplier<String> sayHello = () -> {
    counter.value += 1; // counter final, но его поле мутабельно
    return "hello";
};
```
Ну и есть мутабельные готовые `Atomic*` варианты всех базовых типов в `java`, поэтому есть такой вариант:
```java
final AtomicInteger counter = new AtomicInteger();
final Supplier<String> sayHello = () -> {
    counter.getAndIncrement(); // или incrementAndGet (это как i++ или ++i)
    return "hello";
};
```

2019-05-28 19:16 UTC, DenisVerkhoturov approved these changes
Огонь, все супер! :smile:

2019-05-28 19:17 UTC, merged