Change some methods in Graph class
DenisVerkhoturov/metamer pull request #55
Opened 2019-07-03 10:58 UTC by AnBrusn

2019-07-03 10:59 UTC, AnBrusn commented on assembler/src/main/java/metamer/graph/Graph.java
> +    public static Graph graph(final int k, final Stream<String> stream) {
Не уверенны, что получился фабричный метод, но мы старались

2019-07-03 11:00 UTC, AnBrusn commented on assembler/src/test/java/metamer/graph/GraphTest.java
> +        assertTrue(gr.nodes().contains(new Node("AA")));
Мы помним, что это не информативно, но ничего лучше мы не придумали :cry

2019-07-03 13:40 UTC, DenisVerkhoturov commented
![](https://github.trello.services/images/mini-trello-icon.png) [Рефакторинг класса Graph](https://trello.com/c/Mqnqin2X/81-%D1%80%D0%B5%D1%84%D0%B0%D0%BA%D1%82%D0%BE%D1%80%D0%B8%D0%BD%D0%B3-%D0%BA%D0%BB%D0%B0%D1%81%D1%81%D0%B0-graph)

2019-07-03 20:07 UTC, DenisVerkhoturov requested changes
Отличная работа, спасибо=)

Есть однака пара замечаний, на равне с ответами на ваши вопросы=)

2019-07-03 20:07 UTC, DenisVerkhoturov commented on assembler/src/main/java/metamer/graph/Graph.java
> +    public static Graph graph(final int k, final Stream<String> stream) {
Да, все верно=) Фабричный метод - это статический метод конструирующий объект на основе аргументов как и конструктор, но в отличие от конструктора, здесь у нас допустимо иметь логику любой сложность, в конструкторе мы не хотим видеть ничего сложнее присваивания аргумментов в поля.

2019-07-03 20:07 UTC, DenisVerkhoturov commented on assembler/src/test/java/metamer/graph/GraphTest.java
> +        assertTrue(gr.nodes().contains(new Node("AA")));
В `hamcrest` есть матчер `containsInAnyOrder`, который подходит для этой цели:
```java
import static org.hamcrest.Matchers.containsInAnyOrder;
import static org.hamcrest.MatcherAssert.assertThat;

@Test
@DisplayName("all nodes should present when create graph")
public void testIfAllNodesArePresent() {
    final Graph graph = graph(3, Stream.of("AATR", "ART"));
    assertThat(graph.nodes(), containsInAnyOrder(
            new Node("AA"), new Node("AT"), new Node("AR"), new Node("TR"), new Node("RT")
    ));
}
```

Обновите, пожалуйста, тесты, чтобы использовались только `assertThat`, если где-то не знаете, смело спрашивайте, на быстрые вопросы я смогу быстро ответить=)

2019-07-03 20:07 UTC, DenisVerkhoturov commented on assembler/src/main/java/metamer/graph/Graph.java
> +        return nodes.values().stream().collect(Collectors.toSet());
Это можно заменить на простое заворачивание в новый `Set`, чтобы не пробегать по всей коллекции снова:
```java
public Set<Node> nodes() {
    return new HashSet<>(nodes.values());
}
```

2019-07-03 20:07 UTC, DenisVerkhoturov commented on assembler/src/main/java/metamer/graph/Graph.java
> +        }
Не уверен, что вы сочтете это более читаемо, но тоже самое можно сделать в функциональном стиле так:
```java
public Set<Edge> edges() {
        return neighbors.entrySet().stream()
                .flatMap(e -> e.getValue().stream().map(n -> new Edge(e.getKey(), n, k)))
                .collect(toSet());
}
```
В `java` правда даже для такой простой вещи довольно много сервисных вещей приходится написать, поэтому не предлагаю переписывать, просто представляю сравнение, чтобы вы знали как еще можно сделать тоже самое=)

2019-07-03 20:07 UTC, DenisVerkhoturov commented on assembler/src/main/java/metamer/assembler/Assembler.java
> +        Graph graph = graph(k, reads);
Пометьте, пожалуйста `graph` как `final`.

2019-07-03 20:07 UTC, DenisVerkhoturov commented on assembler/src/main/java/metamer/graph/Edge.java
> +        return this.kmer;
Вижу еще один баг нашелся и был исправлен=)

2019-07-03 20:07 UTC, DenisVerkhoturov commented on assembler/src/main/java/metamer/graph/Graph.java
> +     * @return set of nodes.
Молодцы, что сразу правите и документацию, она не должна отставать от имплементации=)

2019-07-04 08:47 UTC, DenisVerkhoturov approved these changes

2019-07-04 09:12 UTC, merged