Сheck compability of Java-11, Gradle-5.2 and JUnit-5.2
DenisVerkhoturov/metamer pull request #6
Opened 2019-03-21 14:04 UTC by Sonik-zirael

2019-03-21 18:54 UTC, alex-klimina submitted a review, later dismissed
Looks fine; I've checked tests locally.

2019-03-21 20:21 UTC, DenisVerkhoturov requested changes
Спасибо, отличная работа! :+1: 

Вот пара предложений:

- [x] Я ввел в заблуждение, сказав, что нам нажна `org.hamcrest:hamcrest-library:2.1`, не могла бы ты, заменить эту зависимость на `org.hamcrest:hamcrest-all:1.3`. В дальнейшем, мы будем писать тесты используя описательные способности именно этой библиотеки, а не `assertTrue`, который не соовершает никакой информации об ошибке.

- [x] Давайте так же расширим нашу таску `gradle test`, добавь, пожалуйста, в нее настройки логирования:
```diff
test {
    useJUnitPlatform()
+
+    testLogging {
+        events 'PASSED', 'FAILED', 'SKIPPED'
+        exceptionFormat = 'full'
+        showStackTraces = false
+    }
}
```
Это позволит нам легче интерпретировать результаты билдов.

- [x] Теперь, когда известно, что все собирается и запускается корректно, можно удалить `src/main/java/metamer/Functional.java` и `src/test/java/metamer/FunctionalTest.class`.

- [x] Последним шагом, я попрошу тебя сосквошить всю работу в этой ветке в один коммит. Прочитать об этом можно, например, тут - [Как склеить коммиты и зачем это нужно](https://htmlacademy.ru/blog/27-how-to-squash-commits-and-why-it-is-needed). В результате в этом реквесте должен быть один коммит.

 Если что-то вызывает вопросы, пожалуйста, пиши! :nerd_face:

2019-03-22 14:27 UTC, DenisVerkhoturov approved these changes

2019-03-22 18:01 UTC, DenisVerkhoturov approved these changes
Спасибо, все выглядит отлично! :+1:

2019-03-22 19:16 UTC, alex-klimina approved these changes

2019-03-22 19:17 UTC, merged

2019-04-12 12:30 UTC, DenisVerkhoturov commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Эксперимент] Проверить `Java 11`](https://trello.com/c/E3sl1DqU/18-%D1%8D%D0%BA%D1%81%D0%BF%D0%B5%D1%80%D0%B8%D0%BC%D0%B5%D0%BD%D1%82-%D0%BF%D1%80%D0%BE%D0%B2%D0%B5%D1%80%D0%B8%D1%82%D1%8C-java-11)