Graph assembly
DenisVerkhoturov/metamer pull request #7
Opened 2019-03-29 14:05 UTC by Sonik-zirael

2019-03-29 15:08 UTC, alex-klimina commented on src/test/java/metamer/graph/GraphTest.java
> +        assertThat(gr.nodes.containsKey("AA"), equalTo(true));
Можно написать просто 
`assertTrue(gr.nodes.containsKey("AA"))` 
- будет чуть короче, немного читаемее, без лишних Matcher-ов

2019-03-29 15:29 UTC, Sonik-zirael commented on src/test/java/metamer/graph/GraphTest.java
> +        assertThat(gr.nodes.containsKey("AA"), equalTo(true));
А, хорошо
Я просто думала, мы везде-везде используем hamcrest вместо JUnit

2019-03-29 15:32 UTC, alex-klimina commented on src/test/java/metamer/graph/GraphTest.java
> +        assertThat(gr.nodes.containsKey("AA"), equalTo(true));
Можно это обсудить и договориться :) 
Я не то чтобы против hamcrest-а, я за простоту и читаемость. В идеале кстати подошел бы матчет containsKey, но я не уверена, что он есть в стандатной либе. Тода было бы 
` assertThat(gr.nodes, containsKey("AA"));`
Можно поискать, можно написать свой :) Но это не критично

2019-03-30 19:45 UTC, DenisVerkhoturov requested changes
Спасибо за пулл-реквест, отлично поработала! :+1:
Всего пара замечаний, плюс не забывай про замечания `codacy`=)

2019-03-30 19:45 UTC, DenisVerkhoturov commented on src/main/java/metamer/graph/Graph.java
> +package graph;
Пакет `graph` ведь лежит в пакете `metamer`, в `java` мы указываем полный путь, поэтому должно быть так:
```java
package metamer.graph;
```
Соответственно, то же самое в тесте. Странно, что редактор у тебя не подчеркнул это как ошибку.

2019-03-30 19:45 UTC, DenisVerkhoturov commented on src/test/java/metamer/graph/GraphTest.java
> +        assertTrue(gr.nodes.containsKey("RT"));
Я видел, что вы с Сашей уже этот вопрос обсуждали, но все же. Давай посмотрим на то, как нам такой тест поможет выяснить в чем проблема. Для простоты не будем ломать реализацию, а сломаем тест, добавим в него такую строчку:
```java
assertTrue(gr.nodes.containsKey("Hell yeah"));
```
Очевидно, что наша логика не соответствует такому тесту и тест должен упасть. Что же он нам говорит:
```
metamer.graph.GraphTest > testIfNodeNotPresent() FAILED
    java.lang.AssertionError: 
    Expected: <false>
         but: was <true>
```
Эмм, не очень инфомативно, не правда ли? Что мы можем с этим сделать? Давай сходим в класс `org.hamcrest.Matchers` и посмотрим, какие выразительные способности он нам предлагает.
- Можно сходить на [сайт с документацией](http://hamcrest.org/JavaHamcrest/javadoc/1.3/), но придется руками выбрать пакет `org.hamcrest` и класс `Matchers` в левой панели (так фигово у них дока работает, так, конечно, дал бы прямую ссылку).
- Или если ты пользуешься редактором `Idea`, тогда просто с зажатой кнопкой `Ctrl` кликни на имя класса `Matchers` в импортах. Если предложит, соглашайся скачать исходники, чтобы видеть документацию к методам.
В общем мы можем заметить, что там есть в точности тот матчер, который нам нужен - `hasKey`:
```java
/* ... */
import static org.hamcrest.Matchers.hasKey;
/* ... */
assertThat(gr.nodes, hasKey("Hell yeah"));
/* ... */
```
И проверяем, что нам сообщает наш тест теперь:
```
metamer.graph.GraphTest > testIfAllNodesArePresent() FAILED
    java.lang.AssertionError: 
    Expected: map containing ["Hell yeah"->ANYTHING]
         but: map was [<AA=metamer.graph.Graph$Node@2c0a0184>, <AR=metamer.graph.Graph$Node@33d9ebd5>, <RT=metamer.graph.Graph$Node@5bc668aa>, <AT=metamer.graph.Graph$Node@52f8bde3>, <TR=metamer.graph.Graph$Node@2e829019>]
```
Это, кстати, сразу показывает, что неплохо было бы переопределить `Graph$Node.toString()`.

Мое предложение, переписать эти проверки на использование матчеров. 
**Даже так**, давайте договоримся, что `assertTrue`, `assertFalse` и `assertEquals` находятся под запретом в этом проекте. И даже банальные проверки на `true` записываются вот так:
```java
assertThat(something, is(true));
```

2019-03-30 19:45 UTC, DenisVerkhoturov commented on src/main/java/metamer/graph/Graph.java
> +    Map<String, Node> nodes;
Давай скроем сами поля от внещнего наблюдателя, и дадим на них "геттеры", причем в геттерах нужно производить коммирование коллекции, а не отдавать коллекцию на прямую.

**Пояснение**
Если мы отдаем состояние нашего объекта наружу, то внешний пользователь, может сделать с нашим состоянием все что угодня без нашего ведома - это неприятная ситуация, объект должен полностью контролировать все переходы собственного состояния.
Сейчас, я могу например сделать так
```java
gt.nodes.clean();
```
Что приведет объект `gr` в неконсистентное состояние, так как теперь множества `nodes` и `edges` теперь никак не связаны.
Простой способ исправить это - возвращать в "геттере" копию коллекции, например, так:
```java
public Map<String, Node> getNodes() {
    return new HashMap(this.nodes);
}
```
Вариант еще лучше, это позволить внешнему пользователю, получать нашу коллекцию в формате той коллекции, которая ему нужна, делается это так:
```java
public Stream<Map.Entry<String, Node>> nodes() {
    return this.nodes.entrySet().stream();
}
```
Ну или даже, не множество пар ключт-значение, а множество самих значений или самих ключей, по отдельности, не суть. Главное, что внешний пользователь, может теперь сделать так:
```java
import java.util.stream.Collectors;
/* ... */
gr.nodes().collect(toSet());
```
И получить множество, или сделать `toList()` и получить список, и так далее, может собрать снова в мапу:
```java
import java.util.function.Function;
/* ... */
gr.nodes().collect(toMap(identity(), identity()))
```
Важно понимать, что сама запись `someCollection.stream()` не производит ни каких вычислений, то есть возвращает "обещание", что-то вычислить позже, при условии, что это потребуется.

2019-03-30 19:45 UTC, DenisVerkhoturov commented on src/main/java/metamer/graph/Graph.java
> +            String km1R = st.substring(i + 1, i + k);
Не стоит опасаться расставлять `final`, в случае, когда переменная больше никогда не будет изменяться. Даже более того, я бы рекомендовал всегда ставить `final`, и наборот подходить к вопросу - причина должна быть для того, чтобы наоборот его не ставить.

2019-03-30 19:45 UTC, DenisVerkhoturov commented on src/main/java/metamer/graph/Graph.java
> +        for (int i = 0; i < st.length() - (k - 1); i++) {
Вот очередной неприятный момент `java`, в силу довольно неграмотной иерархии типов, в `java` это не очень применимо, но вообще, это очень распространненый алгорим - `sliding window`. Когда мы пробегаем по какой-то последовательно итерируемой коллекции "окном" какого-то размера. К сожелению, в `java` этот алгоримт не реалигуем в достаточно общей форме, но все же давай определим его хотя бы для строк. Это поможет сократить смысловую нагрузку на метод. Можно сделать например пакет `metamer.utils`, который мы постепенно и будем населять такими вспомогательными функциями. Я ну беду мучить и сразу скажу, что для листов в общем виде он реализуется так, твоя задача, понять как он должен выглядеть для строк (прошу, сразу написать тест, проверяющий эту функцию):
```java
public static <T> Stream<List<T>> sliding(final List<T> list, final int span) {
    return size > list.size()
        ? Stream.empty()
        : IntStream.rangeClosed(0, list.size() - size)
                   .mapToObj(start -> list.subList(start, start + size));
}
```
Опять таки, по скольку мы возвращаем `Stream` внешний пользователь сам может решить, в виде какой коллекции он хочет это видеть.

Соответственно, здесь, мы заменяем цикл, на использование этого стрима.

2019-03-30 19:45 UTC, DenisVerkhoturov commented on src/test/java/metamer/graph/GraphTest.java
> +        assertThat(gr.nodes.containsKey("AT"), equalTo(false));
Как мы уже договорились в другом комментарии, даже банальные проверки на `boolean` делаем через экспрессивные способности матчеров. Хотя, здесь, конечно, заменяем на использование `hasKey`.

Еще один комментарий про `equalTo`, нам ведь сдесь не нужно производить проверку именно на равенство, потому что, примитивы равны и по ссылке, то есть, мы можем заменить этот матчер на `is`, не потеряв семантики и добавив читабельнсоти:
```java
assertThat(gr.nodes.containsKey("AT"), is(false));
```

2019-03-30 19:45 UTC, DenisVerkhoturov commented on src/test/java/metamer/graph/GraphTest.java
> +        assertThat(gr.edges.get(gr.nodes.get("AA")).size(), equalTo(3));
Возвращаясь к матчерам, в `Matchers` есть классный матчер и для этого - `hasSize`:
```java
assertThat(gr.edges.get(gr.nodes.get("AA")), hasSize(3));
```

2019-03-30 19:45 UTC, DenisVerkhoturov commented on src/main/java/metamer/graph/Graph.java
> +                ArrayList<Node> list = this.edges.get(entry.getValue());
Это и условие выше можно заменить такой записью:
```java
ArrayList<Node> list = this.edges.getOrDefault(entry.getValue(), new ArrayList<>());
```

2019-03-30 19:45 UTC, DenisVerkhoturov commented on src/main/java/metamer/graph/Graph.java
> +                        .substring(0, entry2.getKey().length() - 1)) && !list.contains(entry2.getValue())) {
Перегруженное условие, давай вынесем сложное вычисление и дадим ему название, так чтобы в условии проверялись просто две переменные.

2019-03-31 12:33 UTC, ShapovalovaIrina submitted a review, later dismissed

2019-03-31 14:40 UTC, DenisVerkhoturov requested changes
Супер! :+1: 
Вообще, я думаю, что можно принять, а с остальным работать уже в следующих итерациях, но вот тут пара моментов, которые необходимо поправить. А еще сосквош, пожалуйста коммиты, как в прошлый раз.

2019-03-31 14:40 UTC, DenisVerkhoturov commented on src/test/java/metamer/graph/GraphTest.java
> +        assertThat(gr.getNodes().containsKey("AT"), is(false));
Проверки на "не" матчеры так же позволяют композировать:
```java
import static org.hamcrest.Matchers.hasKey;
import static org.hamcrest.Matchers.not;
/* ... */
assertThat(gr.getNodes(), not(hasKey("AT")));
```

2019-03-31 14:40 UTC, DenisVerkhoturov commented on src/main/java/metamer/graph/Graph.java
> +        return new HashMap(this.edges);
Здесь и выше, добавь, пожалуйста, даймонд оператор, а то при компиляции ворнинги будут потому что ты возвращаешь сырую не генерифицированную мапу:
```java
return new HashMap<>(this.edges);
```

2019-03-31 14:40 UTC, DenisVerkhoturov commented on src/test/java/metamer/utils/GraphUtilsTest.java
> +}
Добавь, пожалуйста, символ переноса строки в конце файла.

2019-03-31 14:40 UTC, DenisVerkhoturov commented on src/test/java/metamer/utils/GraphUtilsTest.java
> +        assertThat(list, empty());
Супер! :+1: 
Вижу, ты заглянула в библиотеку матчеров=)

2019-03-31 16:25 UTC, alex-klimina reviewed
Я опоздала сделать ревью вовремя, но с замечаниями Дениса согласна. 
единственное, что смущает - файлы gradle, в первых коммитах их не было, и в мастере уже лежит 11 версия джавы. Откуда они взялись тут?

2019-03-31 17:42 UTC, alex-klimina approved these changes
Отлично!

2019-03-31 17:43 UTC, DenisVerkhoturov approved these changes

2019-03-31 17:43 UTC, merged

2019-04-12 12:30 UTC, DenisVerkhoturov commented
![](https://github.trello.services/images/mini-trello-icon.png) [Реализовать сборку графа](https://trello.com/c/kYnNWqLY/26-%D1%80%D0%B5%D0%B0%D0%BB%D0%B8%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D1%8C-%D1%81%D0%B1%D0%BE%D1%80%D0%BA%D1%83-%D0%B3%D1%80%D0%B0%D1%84%D0%B0)