Fastq
DenisVerkhoturov/metamer pull request #8
Opened 2019-03-30 12:59 UTC by AnBrusn

2019-03-30 22:26 UTC, DenisVerkhoturov requested changes
Спасибо за пулл-реквест! :+1: 
Ниже, ты можешь найти некоторые замечания=)

2019-03-30 22:26 UTC, DenisVerkhoturov commented on build.gradle
> +sourceCompatibility = 1.8
Мы продолжаем работать с версией `11`, думаю, ты закомитила этот файл по ошибке. Необходимо откатить все изменения в нем, в рамках этого пулл-реквеста в него не должно вноситься никаких изменений.

2019-03-30 22:26 UTC, DenisVerkhoturov commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-4.10-bin.zip
И этот файл тоже, не должен меняться.

2019-03-30 22:26 UTC, DenisVerkhoturov commented on settings.gradle
> +rootProject.name = 'pr'
И этот файл тоже, не должен меняться.

2019-03-30 22:26 UTC, DenisVerkhoturov commented on src/main/java/fastq/FastQ.java
> +        return path.substring(path.lastIndexOf(".")).equals(".fastq");
Функционал проверки расширения файла очень полезен, я уверен, что это не единственное место, где он понадобиться. Давай вынесем его в утилитный класс, например, `metamer.utils.Paths`. И объявим там функцию, принимающую `java.nio.file.Path` и во возвращающую `String`. Тогда здесь нам останется лишь проверить, что расширение нужное нам.
```java
public static String extension(final Path path) { /* ... */ }
```
Само расширение файла я предлагаю вынести в константу на уровне класса, пусть она будет публичной, но иммутабельной, и в ней не должно содержаться точки (расширение должно возвращаться уже без точки, всегда не `null` в худшем случае пустая строка):
```java
Paths.extension(filePath).exists(FASTQ_EXTENSION);
```

2019-03-30 22:26 UTC, DenisVerkhoturov commented on src/main/java/fastq/FastQ.java
> +        return null;
Давайте введем политику нулевой толерантности по отношению к `null`. `null` - самый верный способ прийти к ошибке. Чаще всего модно обойтись без него, либо используя `Optional.empty` - если мы ничего не можем вернуть, либо пустую коллекцию. В нашем случае подходит как раз второй вариант.

Предлагаю возвращать `Stream.empty()`, когда нам нечего вернуть.

2019-03-30 22:26 UTC, DenisVerkhoturov commented on src/main/java/fastq/FastQ.java
> +            return Parser.parseString(Files.lines(Paths.get(path)));
Очень компактно! :+1:

2019-03-30 22:26 UTC, DenisVerkhoturov commented on src/main/java/fastq/Parser.java
> +        if (strings.get(0).matches("@\\W*")) {
Тут сразу пара моментов:
- строго говоря, формат идентификатора не специфицирован, там могут написать любой шлак, который захотят, это может быть что угодно, так что единственное, на что мы можем завязываться - это то, что это строка, начинающаяся с символа `@`. 
- Предлагаю вынести этот паттерн в приватную констранту, например:
```java
private final IDENTIFIER_PREFIX = '@';
```
И проверять только префикс (`startsWith(IDENTIFIER_PREFIX)`), потому что проверка всей строки на соответситвие паттеру - это довольно дорогая операция.

2019-03-30 22:26 UTC, DenisVerkhoturov commented on src/main/java/fastq/Parser.java
> +        if (strings.get(0).contains(" ")) {
Вариант с перебором по индексу, тоже рабочий, однако есть способы сделать его чище и избежать заодно сборки стрима в промежуточную коллекцию (что тоже нужно понимать стоит вычислительного времени).

На данный момент, мы можем оставить это решение как есть. Но позже, хотелось бы оптимизировать эту логику. Оптимизировать будем с использованием `java.util.Spliterator` и `java.util.stream.StreamSupport`.

2019-03-30 22:26 UTC, DenisVerkhoturov commented on src/main/java/fastq/Parser.java
> +        if (!strings.get(3).matches("[\\!-\\~]+")) {
Мне нравиться твой подход, с тем, что ты все проверяешь на валидность прежде чем продолжать логику, но боюсь, что иногда он избыточен. Просто нужно помнить, что `matches` операция занимающая довольно много времени. В то время как то, что она проверяет в нашем случае - это просто огромные колличества текста. Пока мы можем это оставить, но в будущем, нам нужно будет решить как лучше поступать с этим.

2019-03-30 22:26 UTC, DenisVerkhoturov commented on src/main/java/fastq/Record.java
> +    byte[] sequence;
`sequence`, пожалуй, лучше сделать строкой, так как мы чаще всего будем работать с ней именно в таком виде. Так же предлагаю защитить все поля от мутирования и сделать `public final` и добавтиь конструктор со всеми аргументами. Важно понимать, они от этого не становятся константами - это просто иммутабельное состояние объекта, не более.

2019-03-30 22:26 UTC, DenisVerkhoturov commented on src/test/java/fastq/FastQTest.java
> +        FastQ fastqFile = new FastQ("testdata/test.fastq");
Зашивать абсолютные пути в код - это крайне плохо. Например, у меня на машине эти тесты падают, потмоту что у меня на машине таких файлов нет. Так же тесты упадут на винде. Кроссплатформенная работа с путями - это довольно простая тема. Все что нам нужно - это класс `java.nio.file.Path` и его статический конструктор `java.nio.file.Paths#get(String | Uri): Path` (ты уже использоватала его в своем коде), дальше мы принимаем за правило работать с уровнями файловой системы только по одному за раз с помощью методов класса `Path` - основной это `resolve`:
```java
import java.nio.file.Paths;
/* ... */
final Path fastq = Paths.get(pathFromUser);
final Path parentDirectory = fasta.getParent();
final Path fileName = fasta.getFileName();
final Path outputFile = parentDirectory.resolve("output_" + fileName);
```
Кроме момента про способ работы с путями, важно сказать, что в случае с тестами, можно просто положить файлы, которые необходимы тебе для тестов в тестовые ресурсы.  Например, твои файлы должны лежать тут:
```
.
└── src
    └── test
        └── resources
            └── metamer
                └── fastq
                    ├── out.txt
                    └── out.fastq
```
И так далее.

И читать тогда существующие ресурсы можно так:
```java
private Path testResource(final String filename) throws URISyntaxException {
    return Paths.get(getClass().getResource(filename).toURI());
}
```
Соответственно обращение будет таким:
```java
assertThat(new Fasta().isValidFile(testResource("out.fastq").toString()), is(true));
```
Несуществующие можно просто делать так:
```java
final nonExisting = Paths.get("nonExistingFileName");
```

2019-03-30 22:26 UTC, DenisVerkhoturov commented on src/main/java/fastq/Record.java
> +    byte[] quality;
Так же для этого класса необходимо переопределить методы `equals`, `hashcode` и `toString`.

2019-03-30 22:26 UTC, DenisVerkhoturov commented on src/test/java/fastq/FastQTest.java
> +        assertThat(curRec.quality, is("!!!!".getBytes()));
Когда мы обновим класс `Record`, мы сможем переписать эту логику более компакно и воспользоваться более говорящим матчером:
```java
assertThat(records, contains(
  new Record("MyCoolID", "some description", "ACTGGTCA", "!~+9#hkm".getBytes()),
  new Record("MyVeryBeautifulID", "", "NATC", "!!!!".getBytes())
));
```

2019-03-30 22:26 UTC, DenisVerkhoturov commented on src/test/java/fastq/ParserTest.java
> +        assertThrows(Exception.class, () -> Parser.formRecord(Arrays.asList("@ ", "ACTGN", "+", "!!!!!")));
По скольку  мы переключились на `java-11` мы можем использовать теперь фабричные методы коллекций, например, для создания списков:
```java
List.of("A", "C", "G", "T");
```

2019-03-30 22:26 UTC, DenisVerkhoturov commented on testdata/nofastqfile.fast
> ++
Как я писал немного выше, тестовые файлы, переносим в ресурсную папку для тестов.

2019-03-30 22:51 UTC, alex-klimina submitted a review, later dismissed
Спасибо за пулл-реквест, отлично! 
Оставила несколько замечаний по коду, нужно поправить. 
Спасибо за работу!

2019-03-30 22:51 UTC, alex-klimina commented on build.gradle
> +sourceCompatibility = 1.8
Видимо, забыла подтянуть изменения из мастера перед коммитом. Это касается изменений версии джавы, блока  testLogging, файлов gradle, и содержимого settings.gradle. Файлы .gitkeep в мастере думаю тоже лучше оставить :)

2019-03-30 22:51 UTC, alex-klimina commented on testdata/nofastqfile.fast
> +@MyCoolID some description
Тестовые файлы лучше поместить в директорию metamer/src/test/resources/, и создать там папку для файлов, связанных с парсером FastQ - это общепринятая практика, так будет проще искать тестовые файлы

2019-03-30 22:51 UTC, alex-klimina commented on src/main/java/fastq/Parser.java
> +            throw new Exception("Incorrect ID line");
Я бы предложила завести отдельный класс, унаследовав его от RuntimeException, который использовать для обработки ситуаций, связанных с парсингом. 
Во-первых, это сузит область ошибок, сразу будет яснее в какой области произошла проблема - больше конкретики, меньше пересечений с другими возможными ошибками (Exception - слишком общий случай) 
Во-вторых, работать с checked exception-ами довольно утомительно, и не всегда нужна явная проверка. Наследование от RuntimeException позволит избежать объявлений вроде throws Exception в сигнатуре методов и не обязывает обрабатывать эти исключения.

2019-03-30 22:51 UTC, alex-klimina commented on src/test/java/fastq/ParserTest.java
> +        List<Record> ourRecords = recStream.collect(Collectors.toList());
Поскольку recStream используется только одни раз для сборки содержимого stream в список, лучше будет избавиться от лишней 
`List<Record> ourRecords = Parser.parseString(strStream)
                                                            .collect(Collectors.toList());`

2019-03-30 22:51 UTC, alex-klimina commented on src/test/java/fastq/FastQTest.java
> +        FastQ fastqFile = new FastQ("testdata/nofile.fastq");
Я уже писал в комментария к тестовым файлам, лучше переложить их в папку с ресурсами. 
Как работать с такими файлами можно почитать например тут https://stackoverflow.com/questions/28673651/how-to-get-the-path-of-src-test-resources-directory-in-junit

2019-03-30 22:51 UTC, alex-klimina commented on src/main/java/fastq/Parser.java
> +        if (strings.get(0).matches("@\\W*")) {
Выражение "@\\W*", и другие регулярные выражения в этом классе лучше вынести с отдельные константы с именами, коротко говорящими об их назначении. В данном случае может быть что-то вроде 
`private static final String ID_LINE_PATTERN = "@\\W*"`

2019-03-30 22:51 UTC, alex-klimina commented on src/main/java/fastq/FastQ.java
> +    String path;
Чтобы снаружи не было возможности случайно подменить значение переменной, лучше сделать 
`final String path;`
В данном случае эта переменная используется только внутри класса, поэтому больше ничего делать не надо. Если по какой-то причине она нужна снаружи - то нужно будет либо написать геттер (метод getPath), либо можно использовать библиотеку lombok, которая позволяет генерировать такие стандартные методы (и многие другие) просто написав аннотацию над переменной.

2019-03-30 22:51 UTC, alex-klimina commented on src/main/java/fastq/FastQ.java
> +        return null;
Возвращать null - плохая практика, чревата многими пробемами в будущем. Если вернуть нечего, можно возвращать либо Optional<T>, либо пустую коллекцию/стрим. В данному случае подойдет Stream.empty()

2019-03-31 09:54 UTC, Sonik-zirael submitted a review, later dismissed
Молодец 😄

2019-03-31 09:54 UTC, Sonik-zirael commented on src/test/java/fastq/FastQTest.java
> +        FastQ fastqFile = new FastQ("testdata/nofile.fastq");
В защиту Ани могу сказать, что она скорее всего ориентировалась на способ хранения тестовых файлов в Picard'е 🤔

2019-03-31 10:29 UTC, DenisVerkhoturov commented on src/test/java/fastq/FastQTest.java
> +        FastQ fastqFile = new FastQ("testdata/nofile.fastq");
Picard не стоит воспринимать как пример хороших решений. Если сказать честнее, написан он крайне плохо, там многие вещи вызывают вопросы.

2019-03-31 11:23 UTC, DenisVerkhoturov requested changes
Спасибо, очень быстро внесла исправления=) правда похоже объемом замечаний мы тебя скорее сбили с толку!=/

2019-03-31 11:23 UTC, DenisVerkhoturov commented on src/main/java/utils/Paths.java
> +        return path.toString().substring(path.toString().lastIndexOf(".") + 1);
Это опасная реализация, напиши, пожалуйста, к ней тесты, нас интересуют следующие кейсы:

| Path | Expected extension |
|-------|--------------------------|
| "/test/test.tar.gz" | "gz" |
|"/test/test.txt | "txt |
| "test.d/test" | "" |
| "test/test" | "" |

Еще один комментарий, про работу с путями, поскольку тебе нужен не весь путь, а только имя файла, можно сначала взять `path.fileName()`, а потом работать уже с ним.

2019-03-31 11:23 UTC, DenisVerkhoturov commented on src/test/java/fastq/FastQTest.java
> +package fastq;
Оу, еще прошу прощения, не обратил на этот момент при первом ревью. Положи, пожалуйста, свой пакет `fastq` в пакет `metamer`. То есть `package` будет `metamer.fastq`. Соответственно эьто справедливо и для исходников, и для тестов, и для ресурсов.

2019-03-31 11:23 UTC, DenisVerkhoturov commented on src/test/java/fastq/FastQTest.java
> +        } catch (Exception e) {
В тестак не имеет смысла ловить и обрабатывать ошибки (в общем случае), разверни, пожалуйста, логику теста из `try` и просто добавь в сигнатуру метода:
```java
@Test
void testIfFileIsNotFastQ() throws URISyntaxException { /* ... */ }
```
В остальных местах так же.

2019-03-31 11:23 UTC, DenisVerkhoturov commented on src/main/java/fastq/FastQ.java
> +    public FastQ(String path) {
Почему бы нам прямо с `Path` и не работать? `String` - это ведь не гарантия того, что нам передали валидную строку описывающую путь.

2019-03-31 11:23 UTC, DenisVerkhoturov commented on src/main/java/fastq/FastQ.java
> +        File file = new File(path);
Получить `File` по данному `Path` очень легко:
```java
final Path path = Paths.get("some/text.file");
final File file = path.toFile();
```

2019-03-31 11:23 UTC, DenisVerkhoturov commented on src/main/java/fastq/FastQ.java
> +    public Stream<Record> readStreamRecordsFromFile() {
Предлагаю переименовать этот метод просто в `records`, это общая практика, называть методы возвращающие стримы по названию элементов стрима во множественном числе.

2019-03-31 11:23 UTC, DenisVerkhoturov commented on src/main/java/fastq/Record.java
> +}
Переопредели, пожалуйста, для этого класса методы `equals`, `hashCode` и `toString`. Если я правильно помню, `Idea` сама умеет их генерировать, но я давно этим не пользовался и не помню. Но в этом классе нам крайне нужны эти методы.

2019-03-31 11:23 UTC, DenisVerkhoturov commented on src/test/java/fastq/FastQTest.java
> +            assertThat(curRec.quality, is("!!!!".getBytes()));
Соответственно, при переопределенных `equals` и `hashCode` у нас появится возможность переписать этот тест так:
```java
@Test
void testReadRecordsFromFile() throws URISyntaxException {
    final FastQ file = new FastQ(testResource("test.fastq").toString());
    final List<Record> records = file.records().collect(toList());

    assertThat(records, contains(
            new Record("MyCoolID", "some description", "ACTGGTCA", "!~+9#hkm".getBytes()),
            new Record("MyVeryBeautifulID", "", "NATC", "!!!!".getBytes())
    ));
}
```

2019-04-05 21:22 UTC, DenisVerkhoturov submitted a review, later dismissed
Огонь! :+1: 
Переименуй, пожалуйста, коммит, что-нибудь вроде `feat: Add FastQ reading logic`. Переименовать последнйи коммит можно, например, так:
```bash
git commit --amend -m "NEW AWESOME MESSAGE"
```
Только нужно убедиться, что в индексе нет ничего лишнего, что добавиться в коммит, если есть, убрайть файлы обратно в `unstaged`, можно так:
```bash
git reset HEAD .
```

2019-04-06 06:02 UTC, ShapovalovaIrina approved these changes

2019-04-06 08:55 UTC, DenisVerkhoturov approved these changes

2019-04-06 08:58 UTC, merged

2019-04-12 12:31 UTC, DenisVerkhoturov commented
![](https://github.trello.services/images/mini-trello-icon.png) [Реализовать поддержку `fastq`](https://trello.com/c/qzWyiXyv/23-%D1%80%D0%B5%D0%B0%D0%BB%D0%B8%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D1%8C-%D0%BF%D0%BE%D0%B4%D0%B4%D0%B5%D1%80%D0%B6%D0%BA%D1%83-fastq)