feat & test: Add initial version of fasta task
DenisVerkhoturov/metamer pull request #9
Opened 2019-03-30 14:42 UTC by ShapovalovaIrina

2019-03-30 21:37 UTC, DenisVerkhoturov requested changes
Спасибо за пулл-реквест! :+1: 
Ниже, ты можешь найти некоторые комментарии=)

2019-03-30 21:37 UTC, DenisVerkhoturov commented on src/main/java/metamer/fasta/Fasta.java
> +    public boolean isValidFile(String filePath) {
Работу с путями, необходимо переписать на использование `java.nio.file.Path`. То есть все методы, которые работают с путями файловой системы, должны принимать оьъект типа `Path`.

2019-03-30 21:37 UTC, DenisVerkhoturov commented on src/test/java/metamer/fasta/FastaTest.java
> +        assertThat(new Fasta().isValidFile("C:\\test\\out.fasta"), is(true));
Зашивать абсолютные пути в код - это крайне плохо. Например, у меня на машине эти тесты падают, потмоту что у меня на машине таких файлов нет. Кроме того у меня машина под управлением `linux`, соответсвенно, у меня пути имеюсь совершенно другие разделители. Кроссплатформенная работа с путями - это довольно простая тема. Все что нам нужно - это класс `java.nio.file.Path` и его статический конструктор `java.nio.file.Paths#get(String | Uri): Path`, дальше мы принимаем за правило работать с уровнями файловой системы только по одному за раз с помощью методоа класса `Path` - основной это `resolve`:
```java
import java.nio.file.Paths;
/* ... */
final Path fasta = Paths.get(pathFromUser);
final Path parentDirectory = fasta.getParent();
final Path fileName = fasta.getFileName();
final Path outputFile = parentDirectory.resolve("output_" + fileName);
```
Кроме момента про способ работы с путями, важно сказать, что в случае с тестами, можно просто положить файлы, которые необходимы тебе для тестов в тестовые ресурсы.  Например, твои файлы должны лежать тут:
```
.
└── src
    └── test
        └── resources
            └── metamer
                └── fasta
                    ├── out.txt
                    └── out.fasta
```
И так далее.

И читать их тогда существующие ресурсы можно так:
```java
private Path testResource(final String filename) throws URISyntaxException {
    return Paths.get(getClass().getResource(filename).toURI());
}
```
Соответственно обращение будет таким:
```java
assertThat(new Fasta().isValidFile(testResource("out.fasta").toString()), is(true));
```
Несуществующие можно просто делать так:
```java
final nonExisting = Paths.get("nonExistingFileName");
```

2019-03-30 21:37 UTC, DenisVerkhoturov commented on src/test/java/metamer/fasta/ParserTest.java
> +        record.sequence = "ADQLTEEQIAEFKEAFSLFDKDGDGTITTKELGTVMRSLGQNPTEAELQDMINEVDADGNGTID" +
Обращение мутирование состояния объекта из вне - это плохая практика. Давай стараться все объекты делать по возможности иммутабельными. То есть объект полностью инициализируется при создании, для этого нужен полный конструктор, а поля класса рекомендую пометить как `final`, чтобы в будущем предотвратить мутирование и не наткнуться на него снова.
```java
final String uniqueIdentifier = "MCHU";
final String sequence = 
    "ADQLTEEQIAEFKEAFSLFDKDGDGTITTKELGTVMRSLGQNPTEAELQDMINEVDADGNGTID" +
    "FPEFLTMMARKMKDTDSEEEIREAFRVFDKDGNGYISAAELRHVMTNLGEKLTDEEVDEMIREA" +
    "DIDGDGQVNYEEFVQMMTAK*";
final Record record = new Record(uniqueIdentifier, sequence);
```

2019-03-30 21:37 UTC, DenisVerkhoturov commented on src/test/java/metamer/fasta/ParserTest.java
> +        assertThat(new Parser().parseRecords(stream).findFirst().get(), is(expectedString));
Очень рад, что ты добралась до `findFirst`! :+1: Однако, вызывать `get` на `Optional` не безопасно, обычно мы не разворачиваем значения из монад, а продолжаем с ними работать в обертке. Если нам действительно нужно развернуть монаду в значение, мы явно предоставляем поведение по уполчанию, например, `orElseGet` или реже `orElseThrow`. Здесь же нам не нужно разворачивать вовсе, мы просто проверяем значение:
```java
assertThat(new Parser().parseRecords(stream).findFirst(), is(Optional.of(expectedString)));
```

2019-03-30 21:37 UTC, DenisVerkhoturov commented on src/main/java/metamer/fasta/Record.java
> +    public String sequence = "";
Предлагаю защитить все поля от мутрования c помощью модификатора `final`, пусть они остаются `public` обойдемся без "геттеров"=)

2019-03-30 21:37 UTC, DenisVerkhoturov commented on src/main/java/metamer/fasta/Parser.java
> +    private List<String> sequences = new ArrayList<>();
По большому счету `Parser` утилитный класс, у него должно быть накапливаемого состояния, с длинной строки я полностью согласен - очень хорошо, что ты ее обозначила, но от `sequences` давай избавимся. Пусть они прокидываются по методам без сохранения в промежутках в рамках этого класса.

2019-03-30 21:37 UTC, DenisVerkhoturov commented on src/main/java/metamer/fasta/Fasta.java
> +        return (file.isFile() && file.exists());
По скольку у нас `writer` тот факт, что файла по тому пути, по которому мы собираемся писать, еще нет - это абсолютно нормальная ситуация. Нам не следует это проверять. Мы просто должны создать файл, если его не было.

Имело бы смысл наоборот проверять, что файл есть, и выкидывать ошибку пользователю, что он пытается перезаписать существующий файл, но это была бы логика уже не этого класса, а класса его использующего.

2019-03-30 21:37 UTC, DenisVerkhoturov commented on src/main/java/metamer/fasta/Fasta.java
> +        }
Функционал проверки расширения файла очень полезен, я уверен, что это не единственное место, где он понадобиться. Давай вынесем его в утилитный класс, например, `metamer.utils.Paths`. И объявим там функцию, принимающую `java.nio.file.Path` и во возвращающую `String`. Тогда здесь нам останется лишь проверить, что расширение нужное нам.
```java
public static String extension(final Path path) { /* ... */ }
```
Само расширение файла я предлагаю вынести в константу на уровне класса, пусть она будет публичной, но иммутабельной, и в ней не должно содержаться точки (расширение должно возвращаться уже без точки, всегда не `nunll` в худшем случае пустая строка):
```java
Paths.extension(filePath).exists(FASTA_EXTENSION);
```

2019-03-30 21:37 UTC, DenisVerkhoturov commented on src/main/java/metamer/fasta/Fasta.java
> +            stream.forEach((str) -> {
Вот это огонь! :+1: 

Потом если у вас будет желание, можем подключить шикарную библеотеку для работы с монадами - `vavr`. В частности, там есть такая "полу"-монада `Try`, она позволяет описывать вычисления, которые могут провалиться, в более чистой и выразительной семантике.

2019-03-30 21:37 UTC, DenisVerkhoturov commented on src/main/java/metamer/fasta/Fasta.java
> +                throw new NoSuchFileException("Not a file!");
Сейча забавная ситуация, так как ты завернула все эти вычисления в `try`, что эта ошибка, что ошибка выше не будут выброшены внешнему пользователю, а будут отловлены здесь и внешний пользователь никогда не узнает, что что-то пошло не так.
Эти проверки нужно вынести за пределы `try`.

2019-03-31 09:41 UTC, Sonik-zirael submitted a review, later dismissed
Молодец :)

2019-03-31 14:25 UTC, DenisVerkhoturov requested changes
Спасибо за изменения, нужно исправить еще пару моментов=)

2019-03-31 14:25 UTC, DenisVerkhoturov commented on src/main/java/metamer/fasta/Record.java
> +        this.sequence = sequence;
Это хороший подход, делать конструкторы разной полноты, нужно только принять один конструктор за конструктор по умолчанию, а все другие просто вызывают его:
```java
public Record(String uniqueIdentifier, String sequence) {
    this(uniqueIdentifier, "", sequence);
}
```

2019-03-31 14:25 UTC, DenisVerkhoturov commented on src/main/java/metamer/fasta/Record.java
> +}
Переопредели, пожалуйста, методы `equals`, `hashCode` и `toString` для этого класса.

2019-03-31 14:25 UTC, DenisVerkhoturov commented on src/test/java/metamer/fasta/FastaTest.java
> +        } catch (URISyntaxException e) {
- В тестах не особо имеет смысла обрабатывать ошибки, можно смело выносить их в сигнатуру метода.
- Еще `extension` смело можно статически импортировать.
- И давай все же тесты перепишем с использованием матчеров.
```java
import static metamer.utils.Paths.extension;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.not;
import static org.hamcrest.Matchers.is;
/* ... */
@Test
public void testNotFastaFile() throws URISyntaxException {
    Path path = testResource("out.txt");
    assertThat(extension(path), is(not(Fasta.EXTENSION)));
}
```
Исключения в тестах нам интересны, только если мы тестируем случай, когда ожидается исключение, с помощью `assertThrows`, во всех осталвьных случаях, просто выносим в сигнатуру и не паримся.

2019-03-31 14:25 UTC, DenisVerkhoturov commented on src/main/java/metamer/fasta/Fasta.java
> +    public final String FASTA_EXTENSION = "fasta";
Имеет смысл сделать поле `EXTENSION` статическим, потому что оно верно для любого экземляра этого класса. Соответственно обращаться к нему мы будем в таком случае `Fasta.EXTENSION`.

2019-03-31 14:25 UTC, DenisVerkhoturov commented on src/main/java/metamer/fasta/Fasta.java
> +    public void writeRecordsInFile(Path filePath) throws IOException {
Давай упростим имя до простого `write`, нет смысла делать большие сложные названия, потому что при вызове снаружи итак будет понятно на чем оно вызывается.
```java
final Fasta outputFasta = new Fasta(records, "some/output.fasta");
outputFasta.write();
```

2019-03-31 14:25 UTC, DenisVerkhoturov commented on src/main/java/metamer/fasta/Fasta.java
> +    private List<Record> listRecord = new ArrayList<>();
Нужно добавить конструктор, который будет принимать путь к конечному файлу, а `records` перенести в аргументы метода `write`. То есть у нас логика немного наоборот. Путь к файлу - это наше состояние, а записи - это что-то, что дают нам в аргументах.

2019-03-31 16:33 UTC, alex-klimina submitted a review, later dismissed
Супер :)

2019-03-31 16:33 UTC, alex-klimina commented on src/main/java/metamer/fasta/Fasta.java
> +            throw new NoSuchFileException("Not a fasta extension!");
Тут лучше использовать другой класс исключений. NoSuchFileException не совсем корректен в данном случае - файл есть, но не подходит. Мне кажется, IllegalArgumentException подойдет лучше

2019-04-05 21:48 UTC, DenisVerkhoturov submitted a review, later dismissed
Огонь! :+1: 
Переименуй, пожалуйста, коммит, что-нибудь вроде `feat: Add Fasta writing logic`. Переименовать последнйи коммит можно, например, так:
```bash
git commit --amend -m "NEW AWESOME MESSAGE"
```
Только нужно убедиться, что в индексе нет ничего лишнего, что добавиться в коммит, если есть, убрайть файлы обратно в `unstaged`, можно так:
```bash
git reset HEAD .
```

2019-04-06 11:54 UTC, DenisVerkhoturov approved these changes

2019-04-06 12:00 UTC, alex-klimina approved these changes

2019-04-06 12:01 UTC, merged

2019-04-12 12:30 UTC, DenisVerkhoturov commented
![](https://github.trello.services/images/mini-trello-icon.png) [Реализовать поддержку `fasta`](https://trello.com/c/wpM0druc/24-%D1%80%D0%B5%D0%B0%D0%BB%D0%B8%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D1%8C-%D0%BF%D0%BE%D0%B4%D0%B4%D0%B5%D1%80%D0%B6%D0%BA%D1%83-fasta)